// Mocks generated by Mockito 5.4.4 from annotations
// in waste_segregation_app/test/providers/gamification_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i14;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:waste_segregation_app/models/classification_feedback.dart'
    as _i12;
import 'package:waste_segregation_app/models/filter_options.dart' as _i10;
import 'package:waste_segregation_app/models/gamification.dart' as _i2;
import 'package:waste_segregation_app/models/user_profile.dart' as _i8;
import 'package:waste_segregation_app/models/waste_classification.dart' as _i9;
import 'package:waste_segregation_app/providers/gamification_repository.dart'
    as _i6;
import 'package:waste_segregation_app/services/classification_storage_service.dart'
    as _i3;
import 'package:waste_segregation_app/services/cloud_storage_service.dart'
    as _i13;
import 'package:waste_segregation_app/services/storage_service.dart' as _i5;
import 'package:waste_segregation_app/services/user_profile_storage_service.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGamificationProfile_0 extends _i1.SmartFake
    implements _i2.GamificationProfile {
  _FakeGamificationProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAchievement_1 extends _i1.SmartFake implements _i2.Achievement {
  _FakeAchievement_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClassificationStorageService_2 extends _i1.SmartFake
    implements _i3.ClassificationStorageService {
  _FakeClassificationStorageService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfileStorageService_3 extends _i1.SmartFake
    implements _i4.UserProfileStorageService {
  _FakeUserProfileStorageService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClassificationSaveResult_4 extends _i1.SmartFake
    implements _i5.ClassificationSaveResult {
  _FakeClassificationSaveResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageService_5 extends _i1.SmartFake
    implements _i5.StorageService {
  _FakeStorageService_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GamificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationRepository extends _i1.Mock
    implements _i6.GamificationRepository {
  MockGamificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.GamificationProfile> getProfile(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i7.Future<_i2.GamificationProfile>.value(
            _FakeGamificationProfile_0(
          this,
          Invocation.method(
            #getProfile,
            [],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i7.Future<_i2.GamificationProfile>);

  @override
  _i7.Future<void> saveProfile(_i2.GamificationProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProfile,
          [profile],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.Achievement> claimReward(
    String? achievementId,
    _i2.GamificationProfile? currentProfile,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #claimReward,
          [
            achievementId,
            currentProfile,
          ],
        ),
        returnValue: _i7.Future<_i2.Achievement>.value(_FakeAchievement_1(
          this,
          Invocation.method(
            #claimReward,
            [
              achievementId,
              currentProfile,
            ],
          ),
        )),
      ) as _i7.Future<_i2.Achievement>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i5.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ClassificationStorageService get classificationStorage =>
      (super.noSuchMethod(
        Invocation.getter(#classificationStorage),
        returnValue: _FakeClassificationStorageService_2(
          this,
          Invocation.getter(#classificationStorage),
        ),
      ) as _i3.ClassificationStorageService);

  @override
  _i4.UserProfileStorageService get profileStorage => (super.noSuchMethod(
        Invocation.getter(#profileStorage),
        returnValue: _FakeUserProfileStorageService_3(
          this,
          Invocation.getter(#profileStorage),
        ),
      ) as _i4.UserProfileStorageService);

  @override
  _i7.Future<void> saveUserProfile(_i8.UserProfile? userProfile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [userProfile],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateTrainingConsent(
          _i8.TrainingConsent? trainingConsent) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrainingConsent,
          [trainingConsent],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> grantTrainingConsent({required String? source}) =>
      (super.noSuchMethod(
        Invocation.method(
          #grantTrainingConsent,
          [],
          {#source: source},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> revokeTrainingConsent({String? source = r'settings'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeTrainingConsent,
          [],
          {#source: source},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i8.UserProfile?> getCurrentUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserProfile,
          [],
        ),
        returnValue: _i7.Future<_i8.UserProfile?>.value(),
      ) as _i7.Future<_i8.UserProfile?>);

  @override
  _i7.Future<void> clearUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #clearUserInfo,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> saveClassification(
    _i9.WasteClassification? classification, {
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassification,
          [classification],
          {#force: force},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.ClassificationSaveResult> saveClassificationWithResult(
    _i9.WasteClassification? classification, {
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassificationWithResult,
          [classification],
          {#force: force},
        ),
        returnValue: _i7.Future<_i5.ClassificationSaveResult>.value(
            _FakeClassificationSaveResult_4(
          this,
          Invocation.method(
            #saveClassificationWithResult,
            [classification],
            {#force: force},
          ),
        )),
      ) as _i7.Future<_i5.ClassificationSaveResult>);

  @override
  _i7.Future<String?> findDuplicateClassificationId(
          _i9.WasteClassification? classification) =>
      (super.noSuchMethod(
        Invocation.method(
          #findDuplicateClassificationId,
          [classification],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<List<_i9.WasteClassification>> getAllClassifications(
          {_i10.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllClassifications,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i7.Future<List<_i9.WasteClassification>>.value(
            <_i9.WasteClassification>[]),
      ) as _i7.Future<List<_i9.WasteClassification>>);

  @override
  _i7.Future<List<_i9.WasteClassification>> getClassificationsWithPagination({
    _i10.FilterOptions? filterOptions,
    int? pageSize = 20,
    int? page = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsWithPagination,
          [],
          {
            #filterOptions: filterOptions,
            #pageSize: pageSize,
            #page: page,
          },
        ),
        returnValue: _i7.Future<List<_i9.WasteClassification>>.value(
            <_i9.WasteClassification>[]),
      ) as _i7.Future<List<_i9.WasteClassification>>);

  @override
  _i7.Future<int> getClassificationsCount(
          {_i10.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsCount,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<String> exportClassificationsToCSV(
          {_i10.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportClassificationsToCSV,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i7.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #exportClassificationsToCSV,
            [],
            {#filterOptions: filterOptions},
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> deleteClassification(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteClassification,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearAllClassifications,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveSettings({
    required bool? isDarkMode,
    required bool? isGoogleSyncEnabled,
    DateTime? lastCloudSync,
    bool? allowHistoryFeedback,
    int? feedbackTimeframeDays,
    bool? notifications,
    bool? eduNotifications,
    bool? gamificationNotifications,
    bool? reminderNotifications,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [],
          {
            #isDarkMode: isDarkMode,
            #isGoogleSyncEnabled: isGoogleSyncEnabled,
            #lastCloudSync: lastCloudSync,
            #allowHistoryFeedback: allowHistoryFeedback,
            #feedbackTimeframeDays: feedbackTimeframeDays,
            #notifications: notifications,
            #eduNotifications: eduNotifications,
            #gamificationNotifications: gamificationNotifications,
            #reminderNotifications: reminderNotifications,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateLastCloudSync(DateTime? timestamp) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastCloudSync,
          [timestamp],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<DateTime?> getLastCloudSync() => (super.noSuchMethod(
        Invocation.method(
          #getLastCloudSync,
          [],
        ),
        returnValue: _i7.Future<DateTime?>.value(),
      ) as _i7.Future<DateTime?>);

  @override
  _i7.Future<Map<String, dynamic>> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i9.WasteClassification?> getCachedClassification(String? hash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedClassification,
          [hash],
        ),
        returnValue: _i7.Future<_i9.WasteClassification?>.value(),
      ) as _i7.Future<_i9.WasteClassification?>);

  @override
  _i7.Future<void> saveCachedClassification(
    String? hash,
    _i9.WasteClassification? classification,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCachedClassification,
          [
            hash,
            classification,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> exportUserData() => (super.noSuchMethod(
        Invocation.method(
          #exportUserData,
          [],
        ),
        returnValue: _i7.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #exportUserData,
            [],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> importUserData(String? jsonData) => (super.noSuchMethod(
        Invocation.method(
          #importUserData,
          [jsonData],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearClassifications,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllUserData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveAnalyticsEvents(List<dynamic>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalyticsEvents,
          [events],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> loadAnalyticsEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAnalyticsEvents,
          [],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<int> getGuestDataMigrationCount() => (super.noSuchMethod(
        Invocation.method(
          #getGuestDataMigrationCount,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> migrateGuestDataToCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #migrateGuestDataToCurrentUser,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  List<_i9.WasteClassification> applyFiltersToClassifications(
    List<_i9.WasteClassification>? classifications,
    _i10.FilterOptions? filterOptions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFiltersToClassifications,
          [
            classifications,
            filterOptions,
          ],
        ),
        returnValue: <_i9.WasteClassification>[],
      ) as List<_i9.WasteClassification>);

  @override
  _i7.Future<int> cleanupDuplicateClassifications() => (super.noSuchMethod(
        Invocation.method(
          #cleanupDuplicateClassifications,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> saveClassificationFeedback(
          _i12.ClassificationFeedback? feedback) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassificationFeedback,
          [feedback],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i12.ClassificationFeedback?> getClassificationFeedback(
          String? dedupKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationFeedback,
          [dedupKey],
        ),
        returnValue: _i7.Future<_i12.ClassificationFeedback?>.value(),
      ) as _i7.Future<_i12.ClassificationFeedback?>);

  @override
  _i7.Future<List<_i12.ClassificationFeedback>>
      getAllClassificationFeedback() => (super.noSuchMethod(
            Invocation.method(
              #getAllClassificationFeedback,
              [],
            ),
            returnValue: _i7.Future<List<_i12.ClassificationFeedback>>.value(
                <_i12.ClassificationFeedback>[]),
          ) as _i7.Future<List<_i12.ClassificationFeedback>>);

  @override
  _i7.Future<void> migrateOldClassifications() => (super.noSuchMethod(
        Invocation.method(
          #migrateOldClassifications,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> migrateThumbnails() => (super.noSuchMethod(
        Invocation.method(
          #migrateThumbnails,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cleanUpOrphanedThumbnails() => (super.noSuchMethod(
        Invocation.method(
          #cleanUpOrphanedThumbnails,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> migrateImagePathsToRelative() => (super.noSuchMethod(
        Invocation.method(
          #migrateImagePathsToRelative,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [CloudStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudStorageService extends _i1.Mock
    implements _i13.CloudStorageService {
  MockCloudStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.StorageService get localStorageService => (super.noSuchMethod(
        Invocation.getter(#localStorageService),
        returnValue: _FakeStorageService_5(
          this,
          Invocation.getter(#localStorageService),
        ),
      ) as _i5.StorageService);

  @override
  _i7.Future<void> saveUserProfileToFirestore(
    _i8.UserProfile? userProfile, {
    bool? useBatching = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfileToFirestore,
          [userProfile],
          {#useBatching: useBatching},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveClassificationWithSync(
    _i9.WasteClassification? classification,
    bool? isGoogleSyncEnabled, {
    bool? processGamification = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassificationWithSync,
          [
            classification,
            isGoogleSyncEnabled,
          ],
          {#processGamification: processGamification},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateClassificationInCloud(
          _i9.WasteClassification? classification) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateClassificationInCloud,
          [classification],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> batchUpdateClassificationsInCloud(
          List<_i9.WasteClassification>? classifications) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateClassificationsInCloud,
          [classifications],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i9.WasteClassification>> getAllClassificationsWithCloudSync(
          bool? isGoogleSyncEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllClassificationsWithCloudSync,
          [isGoogleSyncEnabled],
        ),
        returnValue: _i7.Future<List<_i9.WasteClassification>>.value(
            <_i9.WasteClassification>[]),
      ) as _i7.Future<List<_i9.WasteClassification>>);

  @override
  _i7.Future<int> syncAllLocalClassificationsToCloud() => (super.noSuchMethod(
        Invocation.method(
          #syncAllLocalClassificationsToCloud,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> syncCloudToLocal() => (super.noSuchMethod(
        Invocation.method(
          #syncCloudToLocal,
          [],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> clearCloudData() => (super.noSuchMethod(
        Invocation.method(
          #clearCloudData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteUserStorageBlobs(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserStorageBlobs,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> saveClassificationFeedbackToCloud(
          _i12.ClassificationFeedback? feedback) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassificationFeedbackToCloud,
          [feedback],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> checkClassificationFeedbackExists(String? feedbackId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkClassificationFeedbackExists,
          [feedbackId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<String> uploadImageForBatchProcessing(
    _i14.File? imageFile,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImageForBatchProcessing,
          [
            imageFile,
            userId,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImageForBatchProcessing,
            [
              imageFile,
              userId,
            ],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> updateLeaderboardPrivacyPreference(
          _i8.UserProfile? userProfile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLeaderboardPrivacyPreference,
          [userProfile],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
