// Mocks generated by Mockito 5.4.4 from annotations
// in waste_segregation_app/test/providers/leaderboard_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:waste_segregation_app/models/classification_feedback.dart'
    as _i12;
import 'package:waste_segregation_app/models/filter_options.dart' as _i10;
import 'package:waste_segregation_app/models/leaderboard.dart' as _i6;
import 'package:waste_segregation_app/models/user_profile.dart' as _i8;
import 'package:waste_segregation_app/models/waste_classification.dart' as _i9;
import 'package:waste_segregation_app/services/classification_storage_service.dart'
    as _i2;
import 'package:waste_segregation_app/services/leaderboard_service.dart' as _i4;
import 'package:waste_segregation_app/services/storage_service.dart' as _i7;
import 'package:waste_segregation_app/services/user_profile_storage_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClassificationStorageService_0 extends _i1.SmartFake
    implements _i2.ClassificationStorageService {
  _FakeClassificationStorageService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfileStorageService_1 extends _i1.SmartFake
    implements _i3.UserProfileStorageService {
  _FakeUserProfileStorageService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LeaderboardService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeaderboardService extends _i1.Mock
    implements _i4.LeaderboardService {
  MockLeaderboardService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.LeaderboardEntry>> getTopNEntries(int? limit) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopNEntries,
          [limit],
        ),
        returnValue: _i5.Future<List<_i6.LeaderboardEntry>>.value(
            <_i6.LeaderboardEntry>[]),
      ) as _i5.Future<List<_i6.LeaderboardEntry>>);

  @override
  _i5.Future<_i6.LeaderboardEntry?> getUserEntry(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserEntry,
          [userId],
        ),
        returnValue: _i5.Future<_i6.LeaderboardEntry?>.value(),
      ) as _i5.Future<_i6.LeaderboardEntry?>);

  @override
  _i5.Future<int?> getCurrentUserRank(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserRank,
          [userId],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i7.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClassificationStorageService get classificationStorage =>
      (super.noSuchMethod(
        Invocation.getter(#classificationStorage),
        returnValue: _FakeClassificationStorageService_0(
          this,
          Invocation.getter(#classificationStorage),
        ),
      ) as _i2.ClassificationStorageService);

  @override
  _i3.UserProfileStorageService get profileStorage => (super.noSuchMethod(
        Invocation.getter(#profileStorage),
        returnValue: _FakeUserProfileStorageService_1(
          this,
          Invocation.getter(#profileStorage),
        ),
      ) as _i3.UserProfileStorageService);

  @override
  _i5.Future<void> saveUserProfile(_i8.UserProfile? userProfile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [userProfile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i8.UserProfile?> getCurrentUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i8.UserProfile?>.value(),
      ) as _i5.Future<_i8.UserProfile?>);

  @override
  _i5.Future<void> clearUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #clearUserInfo,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> saveClassification(
    _i9.WasteClassification? classification, {
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassification,
          [classification],
          {#force: force},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.WasteClassification>> getAllClassifications(
          {_i10.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllClassifications,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i5.Future<List<_i9.WasteClassification>>.value(
            <_i9.WasteClassification>[]),
      ) as _i5.Future<List<_i9.WasteClassification>>);

  @override
  _i5.Future<List<_i9.WasteClassification>> getClassificationsWithPagination({
    _i10.FilterOptions? filterOptions,
    int? pageSize = 20,
    int? page = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsWithPagination,
          [],
          {
            #filterOptions: filterOptions,
            #pageSize: pageSize,
            #page: page,
          },
        ),
        returnValue: _i5.Future<List<_i9.WasteClassification>>.value(
            <_i9.WasteClassification>[]),
      ) as _i5.Future<List<_i9.WasteClassification>>);

  @override
  _i5.Future<int> getClassificationsCount(
          {_i10.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsCount,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String> exportClassificationsToCSV(
          {_i10.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportClassificationsToCSV,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i5.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #exportClassificationsToCSV,
            [],
            {#filterOptions: filterOptions},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> deleteClassification(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteClassification,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearAllClassifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveSettings({
    required bool? isDarkMode,
    required bool? isGoogleSyncEnabled,
    DateTime? lastCloudSync,
    bool? allowHistoryFeedback,
    int? feedbackTimeframeDays,
    bool? notifications,
    bool? eduNotifications,
    bool? gamificationNotifications,
    bool? reminderNotifications,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [],
          {
            #isDarkMode: isDarkMode,
            #isGoogleSyncEnabled: isGoogleSyncEnabled,
            #lastCloudSync: lastCloudSync,
            #allowHistoryFeedback: allowHistoryFeedback,
            #feedbackTimeframeDays: feedbackTimeframeDays,
            #notifications: notifications,
            #eduNotifications: eduNotifications,
            #gamificationNotifications: gamificationNotifications,
            #reminderNotifications: reminderNotifications,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateLastCloudSync(DateTime? timestamp) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastCloudSync,
          [timestamp],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<DateTime?> getLastCloudSync() => (super.noSuchMethod(
        Invocation.method(
          #getLastCloudSync,
          [],
        ),
        returnValue: _i5.Future<DateTime?>.value(),
      ) as _i5.Future<DateTime?>);

  @override
  _i5.Future<Map<String, dynamic>> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i9.WasteClassification?> getCachedClassification(String? hash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedClassification,
          [hash],
        ),
        returnValue: _i5.Future<_i9.WasteClassification?>.value(),
      ) as _i5.Future<_i9.WasteClassification?>);

  @override
  _i5.Future<void> saveCachedClassification(
    String? hash,
    _i9.WasteClassification? classification,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCachedClassification,
          [
            hash,
            classification,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> exportUserData() => (super.noSuchMethod(
        Invocation.method(
          #exportUserData,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #exportUserData,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> importUserData(String? jsonData) => (super.noSuchMethod(
        Invocation.method(
          #importUserData,
          [jsonData],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearClassifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllUserData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveAnalyticsEvents(List<dynamic>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalyticsEvents,
          [events],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> loadAnalyticsEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAnalyticsEvents,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<int> getGuestDataMigrationCount() => (super.noSuchMethod(
        Invocation.method(
          #getGuestDataMigrationCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> migrateGuestDataToCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #migrateGuestDataToCurrentUser,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  List<_i9.WasteClassification> applyFiltersToClassifications(
    List<_i9.WasteClassification>? classifications,
    _i10.FilterOptions? filterOptions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFiltersToClassifications,
          [
            classifications,
            filterOptions,
          ],
        ),
        returnValue: <_i9.WasteClassification>[],
      ) as List<_i9.WasteClassification>);

  @override
  _i5.Future<int> cleanupDuplicateClassifications() => (super.noSuchMethod(
        Invocation.method(
          #cleanupDuplicateClassifications,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> saveClassificationFeedback(
          _i12.ClassificationFeedback? feedback) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassificationFeedback,
          [feedback],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i12.ClassificationFeedback?> getClassificationFeedback(
          String? dedupKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationFeedback,
          [dedupKey],
        ),
        returnValue: _i5.Future<_i12.ClassificationFeedback?>.value(),
      ) as _i5.Future<_i12.ClassificationFeedback?>);

  @override
  _i5.Future<List<_i12.ClassificationFeedback>>
      getAllClassificationFeedback() => (super.noSuchMethod(
            Invocation.method(
              #getAllClassificationFeedback,
              [],
            ),
            returnValue: _i5.Future<List<_i12.ClassificationFeedback>>.value(
                <_i12.ClassificationFeedback>[]),
          ) as _i5.Future<List<_i12.ClassificationFeedback>>);

  @override
  _i5.Future<void> migrateOldClassifications() => (super.noSuchMethod(
        Invocation.method(
          #migrateOldClassifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> migrateThumbnails() => (super.noSuchMethod(
        Invocation.method(
          #migrateThumbnails,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cleanUpOrphanedThumbnails() => (super.noSuchMethod(
        Invocation.method(
          #cleanUpOrphanedThumbnails,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> migrateImagePathsToRelative() => (super.noSuchMethod(
        Invocation.method(
          #migrateImagePathsToRelative,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
