targets:
  $default:
    sources:
      exclude:
        - test/**
        - "**/*.g.dart"
        - "**/*.freezed.dart"
        - "**/*.mocks.dart"
        - integration_test_disabled/**
        - scripts/**