name: waste_segregation_app
description: An app to help users properly segregate waste using AI classification.
publish_to: 'none'

version: 0.1.6+99

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  provider: ^6.1.1
  http: ^1.1.0
  dio: ^5.0.0
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.9.0
  # google_sign_in upgraded in Firebase section to ensure compatibility
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0 # Added for Google API authentication
  share_plus: ^7.2.1  # Downgraded to a version that works with our setup
  cross_file: ^0.3.3+8  # Required for XFile for share_plus
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  openai_api: ^0.2.0  # For OpenAI API fallback
  crypto: ^3.0.3  # For SHA-256 hashing
  image: ^4.0.17  # For image preprocessing
  google_mobile_ads: ^6.0.0  # Updated for iOS compatibility
  fl_chart: ^0.68.0  # For data visualization in dashboard
  flutter_markdown: ^0.6.18  # For displaying markdown documents
  intl: ^0.20.2  # For internationalization and date formatting
  webview_flutter: ^4.8.0  # For webview integration
  # Updated Firebase dependencies with web-compatible versions
  firebase_core: ^3.13.0  # Updated for iOS compatibility
  firebase_auth: ^5.5.3  # Updated for iOS compatibility
  google_sign_in: ^6.3.0  # Updated for iOS compatibility
  firebase_crashlytics: ^4.3.5
  firebase_performance: ^0.10.1+5
  firebase_messaging: ^15.1.6  # For FCM token management
  cloud_firestore: ^5.6.7  # For family data and real-time sync
  firebase_dynamic_links: ^6.1.5
  qr_flutter: ^4.1.0  # For QR code generation
  # mobile_scanner: ^4.0.1  # Temporarily disabled due to dependency conflicts
  video_player: ^2.9.5
  url_launcher: ^6.3.0  # For launching URLs and making phone calls
  uuid: ^4.5.0  # For generating unique IDs
  auto_size_text: ^3.0.0  # For responsive text that auto-adjusts font size
  permission_handler: ^11.2.0  # For handling camera and storage permissions
  flutter_riverpod: ^2.4.9
  package_info_plus: ^6.0.0
  connectivity_plus: ^6.0.5  # For network connectivity monitoring
  tutorial_coach_mark: ^1.2.11  # For onboarding coach marks
  flutter_speed_dial: ^7.0.0  # For floating action button speed dial
  flutter_localizations:
    sdk: flutter

  # --- Mapping & Geospatial Dependencies (OpenStreetMap) ---
  flutter_map: ^7.0.2 # High-performance, customizable map solution
  flutter_map_tile_caching: ^9.0.0 # For offline map support
  flutter_map_marker_cluster: ^1.4.0 # For clustering large numbers of markers
  flutter_map_heatmap: ^0.0.8 # For visualizing data density (e.g., waste hotspots)
  geoflutterfire_plus: ^0.0.32 # For Firebase geospatial queries

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  golden_toolkit: ^0.15.0

  share_plus_platform_interface: any
dependency_overrides:
  web: ^0.5.1  # Override to make Firebase Auth Web happy

flutter:
  uses-material-design: true
  generate: true  # enables gen_l10n
  assets:
    - assets/images/
    - assets/icons/
    - assets/docs/
