name: waste_segregation_app
description: An app to help users properly segregate waste using AI classification.
publish_to: 'none'

version: 0.1.6+99

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  provider: ^6.1.1
  http: ^1.1.0
  dio: ^5.0.0
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  camera: ^0.11.1  # Updated to latest
  path_provider: ^2.1.1
  path: ^1.9.0
  # google_sign_in upgraded in Firebase section to ensure compatibility
  googleapis: ^14.0.0  # Updated to latest major
  googleapis_auth: ^2.0.0  # Updated to latest major
  share_plus: ^7.2.2  # Keep current major for compatibility
  cross_file: ^0.3.3+8  # Required for XFile for share_plus
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  openai_api: ^0.3.7  # Updated to latest
  crypto: ^3.0.3  # For SHA-256 hashing
  image: ^4.0.17  # For image preprocessing
  google_mobile_ads: ^6.0.0  # Updated for iOS compatibility
  fl_chart: ^1.0.0  # Updated to new major version with new API
  # REPLACED: flutter_markdown (discontinued) with markdown_widget
  markdown_widget: ^2.3.2+6  # Community-maintained alternative with rich features
  intl: ^0.20.2  # For internationalization and date formatting
  webview_flutter: ^4.13.0  # Updated to latest
  # Updated Firebase dependencies with web-compatible versions
  firebase_core: ^3.14.0  # Updated to latest
  firebase_auth: ^5.6.0  # Updated to latest
  google_sign_in: ^6.3.0  # Updated for iOS compatibility
  firebase_crashlytics: ^4.3.7  # Updated to latest
  firebase_performance: ^0.10.1+7  # Updated to latest
  firebase_messaging: ^15.2.7  # Updated to latest
  cloud_firestore: ^5.6.9  # Updated to latest
  # REPLACED: firebase_dynamic_links (discontinued Aug 25, 2025) with app_links
  app_links: ^6.3.2  # Official replacement for uni_links and deep linking
  qr_flutter: ^4.1.0  # For QR code generation
  # mobile_scanner: ^4.0.1  # Temporarily disabled due to dependency conflicts
  video_player: ^2.10.0  # Updated to latest
  url_launcher: ^6.3.0  # For launching URLs and making phone calls
  uuid: ^4.5.0  # For generating unique IDs
  auto_size_text: ^3.0.0  # For responsive text that auto-adjusts font size
  permission_handler: ^12.0.0+1  # Updated to latest major
  flutter_riverpod: ^2.4.9
  package_info_plus: ^8.3.0  # Updated to resolve web dependency conflict
  connectivity_plus: ^6.0.5  # For network connectivity monitoring
  tutorial_coach_mark: ^1.2.11  # For onboarding coach marks
  flutter_speed_dial: ^7.0.0  # For floating action button speed dial
  flutter_localizations:
    sdk: flutter
  csv: ^6.0.0  # For proper CSV handling with RFC 4180 compliance

  # --- Mapping & Geospatial Dependencies (OpenStreetMap) ---
  flutter_map: ^7.0.2  # Keep current major for compatibility with heatmap
  flutter_map_tile_caching: ^9.1.4  # Keep compatible with flutter_map
  flutter_map_marker_cluster: ^1.4.0 # For clustering large numbers of markers
  flutter_map_heatmap: ^0.0.8 # For visualizing data density (e.g., waste hotspots)
  geoflutterfire_plus: ^0.0.32 # For Firebase geospatial queries

  flutter_markdown: any
  firebase_dynamic_links: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Keep current for compatibility
  build_runner: ^2.4.13  # Keep current for compatibility
  json_serializable: ^6.8.0  # Keep current for compatibility
  hive_generator: ^2.0.1
  mockito: ^5.4.4  # Keep compatible with hive_generator
  # REPLACED: golden_toolkit (discontinued) with alchemist
  alchemist: ^0.7.0  # Drop-in replacement for golden tests

  share_plus_platform_interface: ^3.4.0  # Keep compatible with share_plus
  firebase_storage: any
dependency_overrides:
  web: ^1.1.1  # Override to resolve Firebase and package_info_plus conflicts

flutter:
  uses-material-design: true
  generate: true  # enables gen_l10n
  assets:
    - assets/images/
    - assets/icons/
    - assets/docs/
