name: waste_segregation_app
description: An app to help users properly segregate waste using AI classification.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.1.0
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  camera: ^0.11.1
  path_provider: ^2.1.1
  google_sign_in: ^6.1.6
  googleapis: ^13.2.0
  share_plus: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  openai_api: ^0.2.0  # For OpenAI API fallback
  crypto: ^3.0.3  # For SHA-256 hashing
  image: ^4.0.17  # For image preprocessing
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/