name: waste_segregation_app
description: An app to help users properly segregate waste using AI classification.
publish_to: 'none'

version: 0.1.6+99

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  provider: ^6.1.1
  http: ^1.1.0
  dio: ^5.0.0
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  camera: ^0.11.0+2  # Compatible with Dart SDK 3.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  # google_sign_in upgraded in Firebase section to ensure compatibility
  googleapis: ^13.2.0  # Compatible with Dart SDK 3.5.0
  googleapis_auth: ^1.6.0  # Compatible with Dart SDK 3.5.0
  share_plus: ^7.2.2  # Keep current major for compatibility
  cross_file: ^0.3.3+8  # Required for XFile for share_plus
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  openai_api: ^0.3.7  # Updated to latest
  crypto: ^3.0.3  # For SHA-256 hashing
  image: ^4.0.17  # For image preprocessing
  google_mobile_ads: ^5.0.0  # Compatible with Dart SDK 3.5.0 and webview_flutter 4.8.0
  fl_chart: ^0.68.0  # Compatible with Dart SDK 3.5.0
  # REPLACED: flutter_markdown (discontinued) with markdown_widget
  markdown_widget: ^2.3.2+6  # Community-maintained alternative with rich features
  intl: any  # For internationalization and date formatting (version managed by flutter_localizations)
  webview_flutter: ^4.8.0  # Compatible with Dart SDK 3.5.0 and google_mobile_ads
  # Updated Firebase dependencies with web-compatible versions
  firebase_core: ^3.14.0  # Updated to latest
  firebase_auth: ^5.6.0  # Updated to latest
  google_sign_in: ^6.2.0  # Compatible with Dart SDK 3.5.0
  firebase_crashlytics: ^4.3.7  # Updated to latest
  firebase_performance: ^0.10.1+7  # Updated to latest
  firebase_messaging: ^15.2.7  # Updated to latest
  cloud_firestore: ^5.6.9  # Updated to latest
  cloud_functions: ^5.2.7  # For calling Cloud Functions
  # REPLACED: firebase_dynamic_links (discontinued Aug 25, 2025) with app_links
  app_links: ^6.3.2  # Official replacement for uni_links and deep linking
  qr_flutter: ^4.1.0  # For QR code generation
  # mobile_scanner: ^4.0.1  # Temporarily disabled due to dependency conflicts
  video_player: ^2.9.1  # Compatible with current Dart SDK
  url_launcher: ^6.3.0  # For launching URLs and making phone calls
  uuid: ^4.5.0  # For generating unique IDs
  auto_size_text: ^3.0.0  # For responsive text that auto-adjusts font size
  permission_handler: ^12.0.0+1  # Updated to latest major
  flutter_riverpod: ^2.4.9
  package_info_plus: ^8.3.0  # Updated to resolve web dependency conflict
  connectivity_plus: ^6.0.5  # For network connectivity monitoring
  tutorial_coach_mark: ^1.2.11  # For onboarding coach marks
  flutter_speed_dial: ^7.0.0  # For floating action button speed dial
  flutter_localizations:
    sdk: flutter
  csv: ^6.0.0  # For proper CSV handling with RFC 4180 compliance

  # --- Mapping & Geospatial Dependencies (OpenStreetMap) ---
  flutter_map: ^7.0.2  # Keep current major for compatibility with heatmap
  flutter_map_tile_caching: ^9.1.4  # Keep compatible with flutter_map
  flutter_map_marker_cluster: ^1.4.0 # For clustering large numbers of markers
  flutter_map_heatmap: ^0.0.8 # For visualizing data density (e.g., waste hotspots)
  geoflutterfire_plus: ^0.0.32 # For Firebase geospatial queries

  flutter_markdown: any
  firebase_dynamic_links: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Keep current for compatibility
  build_runner: ^2.4.13  # Keep current for compatibility
  json_serializable: ^6.8.0  # Keep current for compatibility
  hive_generator: ^2.0.1
  mockito: ^5.4.4  # Keep compatible with hive_generator
  
  # Golden Testing & Visual Regression
  alchemist: ^0.7.0  # Drop-in replacement for golden tests
  golden_toolkit: ^0.15.0  # For device-size variants and text-scale loops
  
  # E2E Testing - Playwright-style
  patrol: ^3.15.2  # Dart DSL for E2E testing
  patrol_cli: ^2.8.0  # CLI for running patrol tests
  
  # Integration Testing
  integration_test:
    sdk: flutter
  
  # Visual Diff Services (Percy CLI installed separately via npm/yarn)
  
  # Widget Cataloging
  widgetbook: ^3.8.0  # Widget catalog and review
  widgetbook_annotation: ^3.1.0  # Annotations for widgetbook
  widgetbook_generator: ^3.7.0  # Code generation for widgetbook
  
  # Additional Testing Utilities
  fake_async: ^1.3.1  # For testing async code
  mocktail: ^1.0.3  # Modern mocking framework
  network_image_mock: ^2.1.1  # For mocking network images in tests
  
  share_plus_platform_interface: ^3.4.0  # Keep compatible with share_plus
  firebase_storage: any
dependency_overrides:
  web: ^1.1.1  # Override to resolve Firebase and package_info_plus conflicts
  path: 1.8.3  # Pin to version required by integration_test from Flutter SDK
  video_player_platform_interface: ^6.2.0  # Ensure compatibility
  google_sign_in: 6.2.0  # Pin to exact version compatible with Dart SDK 3.5.0
  webview_flutter: 4.8.0  # Pin to version compatible with Dart SDK 3.5.0
  fl_chart: 0.68.0  # Pin to version compatible with Dart SDK 3.5.0
  google_mobile_ads: 5.0.0  # Pin to version compatible with Dart SDK 3.5.0
  googleapis_auth: 1.6.0  # Pin to version compatible with Dart SDK 3.5.0
  googleapis: 13.2.0  # Pin to version compatible with Dart SDK 3.5.0

flutter:
  uses-material-design: true
  generate: true  # enables gen_l10n
  assets:
    - assets/images/
    - assets/icons/
    - assets/docs/
