// Mocks generated by Mockito 5.4.4 from annotations
// in waste_segregation_app/test/widgets/classification_feedback_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:io' as _i11;
import 'dart:typed_data' as _i12;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:waste_segregation_app/models/token_wallet.dart' as _i10;
import 'package:waste_segregation_app/models/waste_classification.dart' as _i6;
import 'package:waste_segregation_app/services/ai_service.dart' as _i7;
import 'package:waste_segregation_app/services/cache_service.dart' as _i2;
import 'package:waste_segregation_app/services/cost_guardrail_service.dart'
    as _i4;
import 'package:waste_segregation_app/services/dynamic_pricing_service.dart'
    as _i3;
import 'package:waste_segregation_app/services/enhanced_api_error_handler.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClassificationCacheService_0 extends _i1.SmartFake
    implements _i2.ClassificationCacheService {
  _FakeClassificationCacheService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDynamicPricingService_1 extends _i1.SmartFake
    implements _i3.DynamicPricingService {
  _FakeDynamicPricingService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCostGuardrailService_2 extends _i1.SmartFake
    implements _i4.CostGuardrailService {
  _FakeCostGuardrailService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEnhancedApiErrorHandler_3 extends _i1.SmartFake
    implements _i5.EnhancedApiErrorHandler {
  _FakeEnhancedApiErrorHandler_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWasteClassification_4 extends _i1.SmartFake
    implements _i6.WasteClassification {
  _FakeWasteClassification_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiService extends _i1.Mock implements _i7.AiService {
  MockAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get openAiBaseUrl => (super.noSuchMethod(
        Invocation.getter(#openAiBaseUrl),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#openAiBaseUrl),
        ),
      ) as String);

  @override
  String get openAiApiKey => (super.noSuchMethod(
        Invocation.getter(#openAiApiKey),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#openAiApiKey),
        ),
      ) as String);

  @override
  String get geminiBaseUrl => (super.noSuchMethod(
        Invocation.getter(#geminiBaseUrl),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#geminiBaseUrl),
        ),
      ) as String);

  @override
  String get geminiApiKey => (super.noSuchMethod(
        Invocation.getter(#geminiApiKey),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#geminiApiKey),
        ),
      ) as String);

  @override
  _i2.ClassificationCacheService get cacheService => (super.noSuchMethod(
        Invocation.getter(#cacheService),
        returnValue: _FakeClassificationCacheService_0(
          this,
          Invocation.getter(#cacheService),
        ),
      ) as _i2.ClassificationCacheService);

  @override
  _i3.DynamicPricingService get pricingService => (super.noSuchMethod(
        Invocation.getter(#pricingService),
        returnValue: _FakeDynamicPricingService_1(
          this,
          Invocation.getter(#pricingService),
        ),
      ) as _i3.DynamicPricingService);

  @override
  _i4.CostGuardrailService get guardrailService => (super.noSuchMethod(
        Invocation.getter(#guardrailService),
        returnValue: _FakeCostGuardrailService_2(
          this,
          Invocation.getter(#guardrailService),
        ),
      ) as _i4.CostGuardrailService);

  @override
  _i5.EnhancedApiErrorHandler get errorHandler => (super.noSuchMethod(
        Invocation.getter(#errorHandler),
        returnValue: _FakeEnhancedApiErrorHandler_3(
          this,
          Invocation.getter(#errorHandler),
        ),
      ) as _i5.EnhancedApiErrorHandler);

  @override
  bool get cachingEnabled => (super.noSuchMethod(
        Invocation.getter(#cachingEnabled),
        returnValue: false,
      ) as bool);

  @override
  String get defaultRegion => (super.noSuchMethod(
        Invocation.getter(#defaultRegion),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#defaultRegion),
        ),
      ) as String);

  @override
  String get defaultLanguage => (super.noSuchMethod(
        Invocation.getter(#defaultLanguage),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#defaultLanguage),
        ),
      ) as String);

  @override
  bool get isCancelled => (super.noSuchMethod(
        Invocation.getter(#isCancelled),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void prepareCancelToken() => super.noSuchMethod(
        Invocation.method(
          #prepareCancelToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cancelAnalysis() => super.noSuchMethod(
        Invocation.method(
          #cancelAnalysis,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool canUseInstantAnalysis({String? model}) => (super.noSuchMethod(
        Invocation.method(
          #canUseInstantAnalysis,
          [],
          {#model: model},
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.AnalysisSpeed getRecommendedAnalysisSpeed({String? model}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedAnalysisSpeed,
          [],
          {#model: model},
        ),
        returnValue: _i10.AnalysisSpeed.batch,
      ) as _i10.AnalysisSpeed);

  @override
  bool isBatchModeEnforced() => (super.noSuchMethod(
        Invocation.method(
          #isBatchModeEnforced,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, double> getBudgetUtilization() => (super.noSuchMethod(
        Invocation.method(
          #getBudgetUtilization,
          [],
        ),
        returnValue: <String, double>{},
      ) as Map<String, double>);

  @override
  double getEstimatedCost({
    String? model,
    int? estimatedInputTokens,
    int? estimatedOutputTokens,
    bool? isBatchMode = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEstimatedCost,
          [],
          {
            #model: model,
            #estimatedInputTokens: estimatedInputTokens,
            #estimatedOutputTokens: estimatedOutputTokens,
            #isBatchMode: isBatchMode,
          },
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double getEstimatedBatchSavings({String? model}) => (super.noSuchMethod(
        Invocation.method(
          #getEstimatedBatchSavings,
          [],
          {#model: model},
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i9.Future<_i6.WasteClassification> analyzeImage(
    _i11.File? imageFile, {
    int? retryCount = 0,
    int? maxRetries = 3,
    String? region,
    String? instructionsLang,
    String? classificationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeImage,
          [imageFile],
          {
            #retryCount: retryCount,
            #maxRetries: maxRetries,
            #region: region,
            #instructionsLang: instructionsLang,
            #classificationId: classificationId,
          },
        ),
        returnValue: _i9.Future<_i6.WasteClassification>.value(
            _FakeWasteClassification_4(
          this,
          Invocation.method(
            #analyzeImage,
            [imageFile],
            {
              #retryCount: retryCount,
              #maxRetries: maxRetries,
              #region: region,
              #instructionsLang: instructionsLang,
              #classificationId: classificationId,
            },
          ),
        )),
      ) as _i9.Future<_i6.WasteClassification>);

  @override
  _i9.Future<_i6.WasteClassification> analyzeWebImage(
    _i12.Uint8List? imageBytes,
    String? imageName, {
    int? retryCount = 0,
    int? maxRetries = 3,
    String? region,
    String? instructionsLang,
    String? classificationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeWebImage,
          [
            imageBytes,
            imageName,
          ],
          {
            #retryCount: retryCount,
            #maxRetries: maxRetries,
            #region: region,
            #instructionsLang: instructionsLang,
            #classificationId: classificationId,
          },
        ),
        returnValue: _i9.Future<_i6.WasteClassification>.value(
            _FakeWasteClassification_4(
          this,
          Invocation.method(
            #analyzeWebImage,
            [
              imageBytes,
              imageName,
            ],
            {
              #retryCount: retryCount,
              #maxRetries: maxRetries,
              #region: region,
              #instructionsLang: instructionsLang,
              #classificationId: classificationId,
            },
          ),
        )),
      ) as _i9.Future<_i6.WasteClassification>);

  @override
  _i9.Future<_i6.WasteClassification> analyzeImageSegments(
    _i11.File? imageFile,
    List<Map<String, dynamic>>? segments, {
    String? region,
    String? instructionsLang,
    String? classificationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeImageSegments,
          [
            imageFile,
            segments,
          ],
          {
            #region: region,
            #instructionsLang: instructionsLang,
            #classificationId: classificationId,
          },
        ),
        returnValue: _i9.Future<_i6.WasteClassification>.value(
            _FakeWasteClassification_4(
          this,
          Invocation.method(
            #analyzeImageSegments,
            [
              imageFile,
              segments,
            ],
            {
              #region: region,
              #instructionsLang: instructionsLang,
              #classificationId: classificationId,
            },
          ),
        )),
      ) as _i9.Future<_i6.WasteClassification>);

  @override
  _i9.Future<_i6.WasteClassification> analyzeImageSegmentsWeb(
    _i12.Uint8List? imageBytes,
    String? imageName,
    List<Map<String, dynamic>>? segments, {
    String? region,
    String? instructionsLang,
    String? classificationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #analyzeImageSegmentsWeb,
          [
            imageBytes,
            imageName,
            segments,
          ],
          {
            #region: region,
            #instructionsLang: instructionsLang,
            #classificationId: classificationId,
          },
        ),
        returnValue: _i9.Future<_i6.WasteClassification>.value(
            _FakeWasteClassification_4(
          this,
          Invocation.method(
            #analyzeImageSegmentsWeb,
            [
              imageBytes,
              imageName,
              segments,
            ],
            {
              #region: region,
              #instructionsLang: instructionsLang,
              #classificationId: classificationId,
            },
          ),
        )),
      ) as _i9.Future<_i6.WasteClassification>);

  @override
  _i9.Future<_i6.WasteClassification> handleUserCorrection(
    _i6.WasteClassification? originalClassification,
    String? userCorrection,
    String? userReason, {
    String? model,
    List<String>? reanalysisModelsTried,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleUserCorrection,
          [
            originalClassification,
            userCorrection,
            userReason,
          ],
          {
            #model: model,
            #reanalysisModelsTried: reanalysisModelsTried,
          },
        ),
        returnValue: _i9.Future<_i6.WasteClassification>.value(
            _FakeWasteClassification_4(
          this,
          Invocation.method(
            #handleUserCorrection,
            [
              originalClassification,
              userCorrection,
              userReason,
            ],
            {
              #model: model,
              #reanalysisModelsTried: reanalysisModelsTried,
            },
          ),
        )),
      ) as _i9.Future<_i6.WasteClassification>);

  @override
  String cleanJsonString(String? rawContent) => (super.noSuchMethod(
        Invocation.method(
          #cleanJsonString,
          [rawContent],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #cleanJsonString,
            [rawContent],
          ),
        ),
      ) as String);

  @override
  _i9.Future<List<Map<String, dynamic>>> segmentImage(dynamic imageSource) =>
      (super.noSuchMethod(
        Invocation.method(
          #segmentImage,
          [imageSource],
        ),
        returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i9.Future<List<Map<String, dynamic>>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
