// Mocks generated by Mockito 5.4.4 from annotations
// in waste_segregation_app/test/screens/community_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:waste_segregation_app/models/community_feed.dart' as _i2;
import 'package:waste_segregation_app/models/filter_options.dart' as _i9;
import 'package:waste_segregation_app/models/gamification.dart' as _i7;
import 'package:waste_segregation_app/models/user_profile.dart' as _i6;
import 'package:waste_segregation_app/models/waste_classification.dart' as _i5;
import 'package:waste_segregation_app/services/community_service.dart' as _i3;
import 'package:waste_segregation_app/services/storage_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCommunityStats_0 extends _i1.SmartFake
    implements _i2.CommunityStats {
  _FakeCommunityStats_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommunityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityService extends _i1.Mock implements _i3.CommunityService {
  MockCommunityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initCommunity() => (super.noSuchMethod(
        Invocation.method(
          #initCommunity,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addFeedItem(_i2.CommunityFeedItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFeedItem,
          [item],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.CommunityFeedItem>> getFeedItems({int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeedItems,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.CommunityFeedItem>>.value(
            <_i2.CommunityFeedItem>[]),
      ) as _i4.Future<List<_i2.CommunityFeedItem>>);

  @override
  _i4.Future<_i2.CommunityStats> getCommunityStats() => (super.noSuchMethod(
        Invocation.method(
          #getCommunityStats,
          [],
        ),
        returnValue: _i4.Future<_i2.CommunityStats>.value(_FakeCommunityStats_0(
          this,
          Invocation.method(
            #getCommunityStats,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CommunityStats>);

  @override
  _i4.Future<_i2.CommunityStats> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: _i4.Future<_i2.CommunityStats>.value(_FakeCommunityStats_0(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CommunityStats>);

  @override
  _i4.Future<void> recordClassification(
    String? category,
    String? subcategory,
    int? points,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordClassification,
          [
            category,
            subcategory,
            points,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recordStreak(
    int? streakDays,
    int? points,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordStreak,
          [
            streakDays,
            points,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> recordAchievement(
    String? title,
    int? points,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordAchievement,
          [
            title,
            points,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> trackClassificationActivity(
    _i5.WasteClassification? classification,
    _i6.UserProfile? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackClassificationActivity,
          [
            classification,
            user,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> trackAchievementActivity(
    _i7.Achievement? achievement,
    _i6.UserProfile? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackAchievementActivity,
          [
            achievement,
            user,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> trackStreakActivity(
    int? streakDays,
    _i6.UserProfile? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackStreakActivity,
          [
            streakDays,
            user,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int calculateActivityPoints(
    _i2.CommunityActivityType? activityType,
    Map<String, dynamic>? metadata,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateActivityPoints,
          [
            activityType,
            metadata,
          ],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<void> batchTrackActivities(
    List<_i5.WasteClassification>? classifications,
    _i6.UserProfile? user,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchTrackActivities,
          [
            classifications,
            user,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRawActivity(Map<String, dynamic>? activityData) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRawActivity,
          [activityData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> generateSampleCommunityData() => (super.noSuchMethod(
        Invocation.method(
          #generateSampleCommunityData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCommunityData() => (super.noSuchMethod(
        Invocation.method(
          #clearCommunityData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupOldActivities({required int? olderThanDays}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupOldActivities,
          [],
          {#olderThanDays: olderThanDays},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i8.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveUserProfile(_i6.UserProfile? userProfile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [userProfile],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.UserProfile?> getCurrentUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserProfile,
          [],
        ),
        returnValue: _i4.Future<_i6.UserProfile?>.value(),
      ) as _i4.Future<_i6.UserProfile?>);

  @override
  _i4.Future<void> clearUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #clearUserInfo,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveClassification(
          _i5.WasteClassification? classification) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassification,
          [classification],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.WasteClassification>> getAllClassifications(
          {_i9.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllClassifications,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i4.Future<List<_i5.WasteClassification>>.value(
            <_i5.WasteClassification>[]),
      ) as _i4.Future<List<_i5.WasteClassification>>);

  @override
  _i4.Future<List<_i5.WasteClassification>> getClassificationsWithPagination({
    _i9.FilterOptions? filterOptions,
    int? pageSize = 20,
    int? page = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsWithPagination,
          [],
          {
            #filterOptions: filterOptions,
            #pageSize: pageSize,
            #page: page,
          },
        ),
        returnValue: _i4.Future<List<_i5.WasteClassification>>.value(
            <_i5.WasteClassification>[]),
      ) as _i4.Future<List<_i5.WasteClassification>>);

  @override
  _i4.Future<int> getClassificationsCount({_i9.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsCount,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<String> exportClassificationsToCSV(
          {_i9.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportClassificationsToCSV,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i4.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #exportClassificationsToCSV,
            [],
            {#filterOptions: filterOptions},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> deleteClassification(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteClassification,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearAllClassifications,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveSettings({
    required bool? isDarkMode,
    required bool? isGoogleSyncEnabled,
    bool? allowHistoryFeedback,
    int? feedbackTimeframeDays,
    bool? notifications,
    bool? eduNotifications,
    bool? gamificationNotifications,
    bool? reminderNotifications,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [],
          {
            #isDarkMode: isDarkMode,
            #isGoogleSyncEnabled: isGoogleSyncEnabled,
            #allowHistoryFeedback: allowHistoryFeedback,
            #feedbackTimeframeDays: feedbackTimeframeDays,
            #notifications: notifications,
            #eduNotifications: eduNotifications,
            #gamificationNotifications: gamificationNotifications,
            #reminderNotifications: reminderNotifications,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i5.WasteClassification?> getCachedClassification(String? hash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedClassification,
          [hash],
        ),
        returnValue: _i4.Future<_i5.WasteClassification?>.value(),
      ) as _i4.Future<_i5.WasteClassification?>);

  @override
  _i4.Future<void> saveCachedClassification(
    String? hash,
    _i5.WasteClassification? classification,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCachedClassification,
          [
            hash,
            classification,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> exportUserData() => (super.noSuchMethod(
        Invocation.method(
          #exportUserData,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #exportUserData,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> importUserData(String? jsonData) => (super.noSuchMethod(
        Invocation.method(
          #importUserData,
          [jsonData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearClassifications,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllUserData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveAnalyticsEvents(List<dynamic>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalyticsEvents,
          [events],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> loadAnalyticsEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAnalyticsEvents,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> getGuestDataMigrationCount() => (super.noSuchMethod(
        Invocation.method(
          #getGuestDataMigrationCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> migrateGuestDataToCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #migrateGuestDataToCurrentUser,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  List<_i5.WasteClassification> applyFiltersToClassifications(
    List<_i5.WasteClassification>? classifications,
    _i9.FilterOptions? filterOptions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFiltersToClassifications,
          [
            classifications,
            filterOptions,
          ],
        ),
        returnValue: <_i5.WasteClassification>[],
      ) as List<_i5.WasteClassification>);

  @override
  _i4.Future<int> cleanupDuplicateClassifications() => (super.noSuchMethod(
        Invocation.method(
          #cleanupDuplicateClassifications,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
