// Mocks generated by Mockito 5.4.4 from annotations
// in waste_segregation_app/test/screens/settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i21;
import 'dart:ui' as _i10;

import 'package:flutter/foundation.dart' as _i5;
import 'package:flutter/material.dart' as _i4;
import 'package:google_sign_in/google_sign_in.dart' as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:waste_segregation_app/models/classification_feedback.dart'
    as _i15;
import 'package:waste_segregation_app/models/filter_options.dart' as _i13;
import 'package:waste_segregation_app/models/premium_feature.dart' as _i9;
import 'package:waste_segregation_app/models/user_profile.dart' as _i11;
import 'package:waste_segregation_app/models/waste_classification.dart' as _i12;
import 'package:waste_segregation_app/services/ad_service.dart' as _i16;
import 'package:waste_segregation_app/services/analytics_service.dart' as _i17;
import 'package:waste_segregation_app/services/classification_storage_service.dart'
    as _i2;
import 'package:waste_segregation_app/services/cloud_storage_service.dart'
    as _i20;
import 'package:waste_segregation_app/services/google_drive_service.dart'
    as _i18;
import 'package:waste_segregation_app/services/navigation_settings_service.dart'
    as _i22;
import 'package:waste_segregation_app/services/premium_service.dart' as _i7;
import 'package:waste_segregation_app/services/storage_service.dart' as _i6;
import 'package:waste_segregation_app/services/user_profile_storage_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClassificationStorageService_0 extends _i1.SmartFake
    implements _i2.ClassificationStorageService {
  _FakeClassificationStorageService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfileStorageService_1 extends _i1.SmartFake
    implements _i3.UserProfileStorageService {
  _FakeUserProfileStorageService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_2 extends _i1.SmartFake implements _i4.Widget {
  _FakeWidget_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i5.DiagnosticLevel? minLevel = _i5.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeStorageService_3 extends _i1.SmartFake
    implements _i6.StorageService {
  _FakeStorageService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PremiumService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPremiumService extends _i1.Mock implements _i7.PremiumService {
  MockPremiumService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isPremiumFeature(String? featureId) => (super.noSuchMethod(
        Invocation.method(
          #isPremiumFeature,
          [featureId],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasActivePremiumPlan() => (super.noSuchMethod(
        Invocation.method(
          #hasActivePremiumPlan,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> setPremiumFeature(
    String? featureId,
    bool? isPremium,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPremiumFeature,
          [
            featureId,
            isPremium,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  List<_i9.PremiumFeature> getPremiumFeatures() => (super.noSuchMethod(
        Invocation.method(
          #getPremiumFeatures,
          [],
        ),
        returnValue: <_i9.PremiumFeature>[],
      ) as List<_i9.PremiumFeature>);

  @override
  List<_i9.PremiumFeature> getComingSoonFeatures() => (super.noSuchMethod(
        Invocation.method(
          #getComingSoonFeatures,
          [],
        ),
        returnValue: <_i9.PremiumFeature>[],
      ) as List<_i9.PremiumFeature>);

  @override
  _i8.Future<void> resetPremiumFeatures() => (super.noSuchMethod(
        Invocation.method(
          #resetPremiumFeatures,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> toggleFeature(String? featureId) => (super.noSuchMethod(
        Invocation.method(
          #toggleFeature,
          [featureId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i6.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClassificationStorageService get classificationStorage =>
      (super.noSuchMethod(
        Invocation.getter(#classificationStorage),
        returnValue: _FakeClassificationStorageService_0(
          this,
          Invocation.getter(#classificationStorage),
        ),
      ) as _i2.ClassificationStorageService);

  @override
  _i3.UserProfileStorageService get profileStorage => (super.noSuchMethod(
        Invocation.getter(#profileStorage),
        returnValue: _FakeUserProfileStorageService_1(
          this,
          Invocation.getter(#profileStorage),
        ),
      ) as _i3.UserProfileStorageService);

  @override
  _i8.Future<void> saveUserProfile(_i11.UserProfile? userProfile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [userProfile],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i11.UserProfile?> getCurrentUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserProfile,
          [],
        ),
        returnValue: _i8.Future<_i11.UserProfile?>.value(),
      ) as _i8.Future<_i11.UserProfile?>);

  @override
  _i8.Future<void> clearUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #clearUserInfo,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> saveClassification(
    _i12.WasteClassification? classification, {
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassification,
          [classification],
          {#force: force},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i12.WasteClassification>> getAllClassifications(
          {_i13.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllClassifications,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i8.Future<List<_i12.WasteClassification>>.value(
            <_i12.WasteClassification>[]),
      ) as _i8.Future<List<_i12.WasteClassification>>);

  @override
  _i8.Future<List<_i12.WasteClassification>> getClassificationsWithPagination({
    _i13.FilterOptions? filterOptions,
    int? pageSize = 20,
    int? page = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsWithPagination,
          [],
          {
            #filterOptions: filterOptions,
            #pageSize: pageSize,
            #page: page,
          },
        ),
        returnValue: _i8.Future<List<_i12.WasteClassification>>.value(
            <_i12.WasteClassification>[]),
      ) as _i8.Future<List<_i12.WasteClassification>>);

  @override
  _i8.Future<int> getClassificationsCount(
          {_i13.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsCount,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<String> exportClassificationsToCSV(
          {_i13.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportClassificationsToCSV,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i8.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #exportClassificationsToCSV,
            [],
            {#filterOptions: filterOptions},
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> deleteClassification(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteClassification,
          [key],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearAllClassifications,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> saveSettings({
    required bool? isDarkMode,
    required bool? isGoogleSyncEnabled,
    DateTime? lastCloudSync,
    bool? allowHistoryFeedback,
    int? feedbackTimeframeDays,
    bool? notifications,
    bool? eduNotifications,
    bool? gamificationNotifications,
    bool? reminderNotifications,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [],
          {
            #isDarkMode: isDarkMode,
            #isGoogleSyncEnabled: isGoogleSyncEnabled,
            #lastCloudSync: lastCloudSync,
            #allowHistoryFeedback: allowHistoryFeedback,
            #feedbackTimeframeDays: feedbackTimeframeDays,
            #notifications: notifications,
            #eduNotifications: eduNotifications,
            #gamificationNotifications: gamificationNotifications,
            #reminderNotifications: reminderNotifications,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateLastCloudSync(DateTime? timestamp) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastCloudSync,
          [timestamp],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<DateTime?> getLastCloudSync() => (super.noSuchMethod(
        Invocation.method(
          #getLastCloudSync,
          [],
        ),
        returnValue: _i8.Future<DateTime?>.value(),
      ) as _i8.Future<DateTime?>);

  @override
  _i8.Future<Map<String, dynamic>> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i12.WasteClassification?> getCachedClassification(String? hash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedClassification,
          [hash],
        ),
        returnValue: _i8.Future<_i12.WasteClassification?>.value(),
      ) as _i8.Future<_i12.WasteClassification?>);

  @override
  _i8.Future<void> saveCachedClassification(
    String? hash,
    _i12.WasteClassification? classification,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCachedClassification,
          [
            hash,
            classification,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> exportUserData() => (super.noSuchMethod(
        Invocation.method(
          #exportUserData,
          [],
        ),
        returnValue: _i8.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #exportUserData,
            [],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> importUserData(String? jsonData) => (super.noSuchMethod(
        Invocation.method(
          #importUserData,
          [jsonData],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearClassifications,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllUserData,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> saveAnalyticsEvents(List<dynamic>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalyticsEvents,
          [events],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> loadAnalyticsEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAnalyticsEvents,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<int> getGuestDataMigrationCount() => (super.noSuchMethod(
        Invocation.method(
          #getGuestDataMigrationCount,
          [],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> migrateGuestDataToCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #migrateGuestDataToCurrentUser,
          [],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  List<_i12.WasteClassification> applyFiltersToClassifications(
    List<_i12.WasteClassification>? classifications,
    _i13.FilterOptions? filterOptions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFiltersToClassifications,
          [
            classifications,
            filterOptions,
          ],
        ),
        returnValue: <_i12.WasteClassification>[],
      ) as List<_i12.WasteClassification>);

  @override
  _i8.Future<int> cleanupDuplicateClassifications() => (super.noSuchMethod(
        Invocation.method(
          #cleanupDuplicateClassifications,
          [],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> saveClassificationFeedback(
          _i15.ClassificationFeedback? feedback) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassificationFeedback,
          [feedback],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i15.ClassificationFeedback?> getClassificationFeedback(
          String? dedupKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationFeedback,
          [dedupKey],
        ),
        returnValue: _i8.Future<_i15.ClassificationFeedback?>.value(),
      ) as _i8.Future<_i15.ClassificationFeedback?>);

  @override
  _i8.Future<List<_i15.ClassificationFeedback>>
      getAllClassificationFeedback() => (super.noSuchMethod(
            Invocation.method(
              #getAllClassificationFeedback,
              [],
            ),
            returnValue: _i8.Future<List<_i15.ClassificationFeedback>>.value(
                <_i15.ClassificationFeedback>[]),
          ) as _i8.Future<List<_i15.ClassificationFeedback>>);

  @override
  _i8.Future<void> migrateOldClassifications() => (super.noSuchMethod(
        Invocation.method(
          #migrateOldClassifications,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> migrateThumbnails() => (super.noSuchMethod(
        Invocation.method(
          #migrateThumbnails,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cleanUpOrphanedThumbnails() => (super.noSuchMethod(
        Invocation.method(
          #cleanUpOrphanedThumbnails,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> migrateImagePathsToRelative() => (super.noSuchMethod(
        Invocation.method(
          #migrateImagePathsToRelative,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [AdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdService extends _i1.Mock implements _i16.AdService {
  MockAdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get shouldShowAds => (super.noSuchMethod(
        Invocation.getter(#shouldShowAds),
        returnValue: false,
      ) as bool);

  @override
  bool get canShowInterstitialAd => (super.noSuchMethod(
        Invocation.getter(#canShowInterstitialAd),
        returnValue: false,
      ) as bool);

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setPremiumStatus(bool? hasPremium) => super.noSuchMethod(
        Invocation.method(
          #setPremiumStatus,
          [hasPremium],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i4.Widget getBannerAd() => (super.noSuchMethod(
        Invocation.method(
          #getBannerAd,
          [],
        ),
        returnValue: _FakeWidget_2(
          this,
          Invocation.method(
            #getBannerAd,
            [],
          ),
        ),
      ) as _i4.Widget);

  @override
  _i8.Future<bool> showInterstitialAd() => (super.noSuchMethod(
        Invocation.method(
          #showInterstitialAd,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  void trackClassificationCompleted() => super.noSuchMethod(
        Invocation.method(
          #trackClassificationCompleted,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool shouldShowInterstitial() => (super.noSuchMethod(
        Invocation.method(
          #shouldShowInterstitial,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setInClassificationFlow(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setInClassificationFlow,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setInEducationalContent(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setInEducationalContent,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setInSettings(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setInSettings,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshBannerAd() => super.noSuchMethod(
        Invocation.method(
          #refreshBannerAd,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i17.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isFirestoreConnected => (super.noSuchMethod(
        Invocation.getter(#isFirestoreConnected),
        returnValue: false,
      ) as bool);

  @override
  int get pendingEventsCount => (super.noSuchMethod(
        Invocation.getter(#pendingEventsCount),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void clearAnalyticsData() => super.noSuchMethod(
        Invocation.method(
          #clearAnalyticsData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackSessionEndLegacy() => super.noSuchMethod(
        Invocation.method(
          #trackSessionEndLegacy,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> trackEvent({
    required String? eventType,
    required String? eventName,
    Map<String, dynamic>? parameters = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackEvent,
          [],
          {
            #eventType: eventType,
            #eventName: eventName,
            #parameters: parameters,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackScreenView(
    String? screenName, {
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackScreenView,
          [screenName],
          {#parameters: parameters},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackUserAction(
    String? actionName, {
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackUserAction,
          [actionName],
          {#parameters: parameters},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackClassification({
    required String? classificationId,
    required String? category,
    required bool? isRecyclable,
    required double? confidence,
    required String? method,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackClassification,
          [],
          {
            #classificationId: classificationId,
            #category: category,
            #isRecyclable: isRecyclable,
            #confidence: confidence,
            #method: method,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackSocialInteraction({
    required String? interactionType,
    required String? targetId,
    String? familyId,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackSocialInteraction,
          [],
          {
            #interactionType: interactionType,
            #targetId: targetId,
            #familyId: familyId,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackAchievement({
    required String? achievementId,
    required String? achievementType,
    required int? pointsAwarded,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackAchievement,
          [],
          {
            #achievementId: achievementId,
            #achievementType: achievementType,
            #pointsAwarded: pointsAwarded,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackError({
    required String? errorType,
    required String? errorMessage,
    String? stackTrace,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackError,
          [],
          {
            #errorType: errorType,
            #errorMessage: errorMessage,
            #stackTrace: stackTrace,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackSessionStart() => (super.noSuchMethod(
        Invocation.method(
          #trackSessionStart,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackSessionEnd() => (super.noSuchMethod(
        Invocation.method(
          #trackSessionEnd,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackPageView(
    String? screenName, {
    String? previousScreen,
    String? navigationMethod,
    int? timeOnPreviousScreen,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackPageView,
          [screenName],
          {
            #previousScreen: previousScreen,
            #navigationMethod: navigationMethod,
            #timeOnPreviousScreen: timeOnPreviousScreen,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackClick({
    required String? elementId,
    required String? screenName,
    required String? elementType,
    String? userIntent,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackClick,
          [],
          {
            #elementId: elementId,
            #screenName: screenName,
            #elementType: elementType,
            #userIntent: userIntent,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackRageClick({
    required String? elementId,
    required String? screenName,
    required int? tapCount,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackRageClick,
          [],
          {
            #elementId: elementId,
            #screenName: screenName,
            #tapCount: tapCount,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackScrollDepth({
    required int? depthPercent,
    required String? screenName,
    String? contentType,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackScrollDepth,
          [],
          {
            #depthPercent: depthPercent,
            #screenName: screenName,
            #contentType: contentType,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackFileClassified({
    required String? classificationId,
    required String? category,
    required double? confidenceScore,
    required int? processingDuration,
    required String? modelVersion,
    String? method,
    bool? resultAccuracy,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackFileClassified,
          [],
          {
            #classificationId: classificationId,
            #category: category,
            #confidenceScore: confidenceScore,
            #processingDuration: processingDuration,
            #modelVersion: modelVersion,
            #method: method,
            #resultAccuracy: resultAccuracy,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackClassificationRetried({
    required String? classificationId,
    required double? originalConfidence,
    required String? retryReason,
    required int? attemptNumber,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackClassificationRetried,
          [],
          {
            #classificationId: classificationId,
            #originalConfidence: originalConfidence,
            #retryReason: retryReason,
            #attemptNumber: attemptNumber,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackSlowResource({
    required String? operationName,
    required int? durationMs,
    required String? resourceType,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackSlowResource,
          [],
          {
            #operationName: operationName,
            #durationMs: durationMs,
            #resourceType: resourceType,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackApiError({
    required String? endpoint,
    required int? statusCode,
    required int? latencyMs,
    int? retryCount,
    String? errorMessage,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackApiError,
          [],
          {
            #endpoint: endpoint,
            #statusCode: statusCode,
            #latencyMs: latencyMs,
            #retryCount: retryCount,
            #errorMessage: errorMessage,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackClientError({
    required String? errorMessage,
    required String? screenName,
    String? stackTrace,
    String? userAction,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackClientError,
          [],
          {
            #errorMessage: errorMessage,
            #screenName: screenName,
            #stackTrace: stackTrace,
            #userAction: userAction,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackPointsEarned({
    required int? pointsAmount,
    required String? sourceAction,
    required int? totalPoints,
    String? category,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackPointsEarned,
          [],
          {
            #pointsAmount: pointsAmount,
            #sourceAction: sourceAction,
            #totalPoints: totalPoints,
            #category: category,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackContentViewed({
    required String? contentId,
    required String? contentType,
    String? source,
    int? userLevel,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackContentViewed,
          [],
          {
            #contentId: contentId,
            #contentType: contentType,
            #source: source,
            #userLevel: userLevel,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> trackContentCompleted({
    required String? contentId,
    required int? timeSpentMs,
    double? completionRate,
    int? quizScore,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackContentCompleted,
          [],
          {
            #contentId: contentId,
            #timeSpentMs: timeSpentMs,
            #completionRate: completionRate,
            #quizScore: quizScore,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> getUserAnalytics(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAnalytics,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getSystemAnalytics(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSystemAnalytics,
          [
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getPopularContent(int? limit) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularContent,
          [limit],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>> getComprehensiveAnalytics({
    required String? userId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComprehensiveAnalytics,
          [],
          {
            #userId: userId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  void trackButtonClick(
    String? buttonName, {
    String? screenName,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackButtonClick,
          [buttonName],
          {#screenName: screenName},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackScreenSwipe(
    String? direction, {
    String? screenName,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackScreenSwipe,
          [direction],
          {#screenName: screenName},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackSearch(
    String? query, {
    int? resultCount,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackSearch,
          [query],
          {#resultCount: resultCount},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackClassificationStarted({String? method}) => super.noSuchMethod(
        Invocation.method(
          #trackClassificationStarted,
          [],
          {#method: method},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackClassificationShared(
    String? classificationId, {
    String? familyId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackClassificationShared,
          [classificationId],
          {#familyId: familyId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackFamilyCreated(
    String? familyId, {
    int? memberCount,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackFamilyCreated,
          [familyId],
          {#memberCount: memberCount},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackFamilyJoined(
    String? familyId, {
    String? invitationId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackFamilyJoined,
          [familyId],
          {#invitationId: invitationId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackReactionAdded(
    String? classificationId,
    String? reactionType, {
    String? familyId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackReactionAdded,
          [
            classificationId,
            reactionType,
          ],
          {#familyId: familyId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GoogleDriveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleDriveService extends _i1.Mock
    implements _i18.GoogleDriveService {
  MockGoogleDriveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i19.GoogleSignInAccount?> signIn() => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
        ),
        returnValue: _i8.Future<_i19.GoogleSignInAccount?>.value(),
      ) as _i8.Future<_i19.GoogleSignInAccount?>);

  @override
  _i8.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> isSignedIn() => (super.noSuchMethod(
        Invocation.method(
          #isSignedIn,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<String> uploadToDrive({
    required String? fileName,
    required String? mimeType,
    required String? content,
    String? folderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadToDrive,
          [],
          {
            #fileName: fileName,
            #mimeType: mimeType,
            #content: content,
            #folderId: folderId,
          },
        ),
        returnValue: _i8.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #uploadToDrive,
            [],
            {
              #fileName: fileName,
              #mimeType: mimeType,
              #content: content,
              #folderId: folderId,
            },
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String> downloadFromDrive(String? fileId) => (super.noSuchMethod(
        Invocation.method(
          #downloadFromDrive,
          [fileId],
        ),
        returnValue: _i8.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #downloadFromDrive,
            [fileId],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String> createFolder(String? folderName) => (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [folderName],
        ),
        returnValue: _i8.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #createFolder,
            [folderName],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String?> findFileOrFolder(
    String? name, {
    bool? isFolder = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findFileOrFolder,
          [name],
          {#isFolder: isFolder},
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<String> backupUserData() => (super.noSuchMethod(
        Invocation.method(
          #backupUserData,
          [],
        ),
        returnValue: _i8.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #backupUserData,
            [],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> restoreUserData(String? fileId) => (super.noSuchMethod(
        Invocation.method(
          #restoreUserData,
          [fileId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, String>>> listBackupFiles() =>
      (super.noSuchMethod(
        Invocation.method(
          #listBackupFiles,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, String>>>.value(
            <Map<String, String>>[]),
      ) as _i8.Future<List<Map<String, String>>>);
}

/// A class which mocks [CloudStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudStorageService extends _i1.Mock
    implements _i20.CloudStorageService {
  MockCloudStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.StorageService get localStorageService => (super.noSuchMethod(
        Invocation.getter(#localStorageService),
        returnValue: _FakeStorageService_3(
          this,
          Invocation.getter(#localStorageService),
        ),
      ) as _i6.StorageService);

  @override
  _i8.Future<void> saveUserProfileToFirestore(
    _i11.UserProfile? userProfile, {
    bool? useBatching = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfileToFirestore,
          [userProfile],
          {#useBatching: useBatching},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> saveClassificationWithSync(
    _i12.WasteClassification? classification,
    bool? isGoogleSyncEnabled, {
    bool? processGamification = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassificationWithSync,
          [
            classification,
            isGoogleSyncEnabled,
          ],
          {#processGamification: processGamification},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateClassificationInCloud(
          _i12.WasteClassification? classification) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateClassificationInCloud,
          [classification],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> batchUpdateClassificationsInCloud(
          List<_i12.WasteClassification>? classifications) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateClassificationsInCloud,
          [classifications],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<_i12.WasteClassification>> getAllClassificationsWithCloudSync(
          bool? isGoogleSyncEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllClassificationsWithCloudSync,
          [isGoogleSyncEnabled],
        ),
        returnValue: _i8.Future<List<_i12.WasteClassification>>.value(
            <_i12.WasteClassification>[]),
      ) as _i8.Future<List<_i12.WasteClassification>>);

  @override
  _i8.Future<int> syncAllLocalClassificationsToCloud() => (super.noSuchMethod(
        Invocation.method(
          #syncAllLocalClassificationsToCloud,
          [],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> syncCloudToLocal() => (super.noSuchMethod(
        Invocation.method(
          #syncCloudToLocal,
          [],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> clearCloudData() => (super.noSuchMethod(
        Invocation.method(
          #clearCloudData,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> saveClassificationFeedbackToCloud(
          _i15.ClassificationFeedback? feedback) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassificationFeedbackToCloud,
          [feedback],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> checkClassificationFeedbackExists(String? feedbackId) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkClassificationFeedbackExists,
          [feedbackId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<String> uploadImageForBatchProcessing(
    _i21.File? imageFile,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImageForBatchProcessing,
          [
            imageFile,
            userId,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImageForBatchProcessing,
            [
              imageFile,
              userId,
            ],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> updateLeaderboardPrivacyPreference(
          _i11.UserProfile? userProfile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLeaderboardPrivacyPreference,
          [userProfile],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [NavigationSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationSettingsService extends _i1.Mock
    implements _i22.NavigationSettingsService {
  MockNavigationSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get bottomNavEnabled => (super.noSuchMethod(
        Invocation.getter(#bottomNavEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get fabEnabled => (super.noSuchMethod(
        Invocation.getter(#fabEnabled),
        returnValue: false,
      ) as bool);

  @override
  String get navigationStyle => (super.noSuchMethod(
        Invocation.getter(#navigationStyle),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#navigationStyle),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> setBottomNavEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setBottomNavEnabled,
          [enabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setFabEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setFabEnabled,
          [enabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setNavigationStyle(String? style) => (super.noSuchMethod(
        Invocation.method(
          #setNavigationStyle,
          [style],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
