// Mocks generated by Mockito 5.4.4 from annotations
// in waste_segregation_app/test/screens/waste_dashboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:waste_segregation_app/models/educational_content.dart' as _i10;
import 'package:waste_segregation_app/models/filter_options.dart' as _i7;
import 'package:waste_segregation_app/models/gamification.dart' as _i2;
import 'package:waste_segregation_app/models/user_profile.dart' as _i5;
import 'package:waste_segregation_app/models/waste_classification.dart' as _i6;
import 'package:waste_segregation_app/services/gamification_service.dart'
    as _i9;
import 'package:waste_segregation_app/services/storage_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGamificationProfile_0 extends _i1.SmartFake
    implements _i2.GamificationProfile {
  _FakeGamificationProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreak_1 extends _i1.SmartFake implements _i2.Streak {
  _FakeStreak_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserPoints_2 extends _i1.SmartFake implements _i2.UserPoints {
  _FakeUserPoints_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i3.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveUserProfile(_i5.UserProfile? userProfile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [userProfile],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.UserProfile?> getCurrentUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserProfile,
          [],
        ),
        returnValue: _i4.Future<_i5.UserProfile?>.value(),
      ) as _i4.Future<_i5.UserProfile?>);

  @override
  _i4.Future<void> clearUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #clearUserInfo,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveClassification(
          _i6.WasteClassification? classification) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassification,
          [classification],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.WasteClassification>> getAllClassifications(
          {_i7.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllClassifications,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i4.Future<List<_i6.WasteClassification>>.value(
            <_i6.WasteClassification>[]),
      ) as _i4.Future<List<_i6.WasteClassification>>);

  @override
  _i4.Future<List<_i6.WasteClassification>> getClassificationsWithPagination({
    _i7.FilterOptions? filterOptions,
    int? pageSize = 20,
    int? page = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsWithPagination,
          [],
          {
            #filterOptions: filterOptions,
            #pageSize: pageSize,
            #page: page,
          },
        ),
        returnValue: _i4.Future<List<_i6.WasteClassification>>.value(
            <_i6.WasteClassification>[]),
      ) as _i4.Future<List<_i6.WasteClassification>>);

  @override
  _i4.Future<int> getClassificationsCount({_i7.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsCount,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<String> exportClassificationsToCSV(
          {_i7.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportClassificationsToCSV,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #exportClassificationsToCSV,
            [],
            {#filterOptions: filterOptions},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> deleteClassification(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteClassification,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearAllClassifications,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveSettings({
    required bool? isDarkMode,
    required bool? isGoogleSyncEnabled,
    bool? allowHistoryFeedback,
    int? feedbackTimeframeDays,
    bool? notifications,
    bool? eduNotifications,
    bool? gamificationNotifications,
    bool? reminderNotifications,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [],
          {
            #isDarkMode: isDarkMode,
            #isGoogleSyncEnabled: isGoogleSyncEnabled,
            #allowHistoryFeedback: allowHistoryFeedback,
            #feedbackTimeframeDays: feedbackTimeframeDays,
            #notifications: notifications,
            #eduNotifications: eduNotifications,
            #gamificationNotifications: gamificationNotifications,
            #reminderNotifications: reminderNotifications,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i6.WasteClassification?> getCachedClassification(String? hash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedClassification,
          [hash],
        ),
        returnValue: _i4.Future<_i6.WasteClassification?>.value(),
      ) as _i4.Future<_i6.WasteClassification?>);

  @override
  _i4.Future<void> saveCachedClassification(
    String? hash,
    _i6.WasteClassification? classification,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCachedClassification,
          [
            hash,
            classification,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> exportUserData() => (super.noSuchMethod(
        Invocation.method(
          #exportUserData,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #exportUserData,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> importUserData(String? jsonData) => (super.noSuchMethod(
        Invocation.method(
          #importUserData,
          [jsonData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearClassifications,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllUserData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveAnalyticsEvents(List<dynamic>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalyticsEvents,
          [events],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> loadAnalyticsEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAnalyticsEvents,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<int> getGuestDataMigrationCount() => (super.noSuchMethod(
        Invocation.method(
          #getGuestDataMigrationCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> migrateGuestDataToCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #migrateGuestDataToCurrentUser,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  List<_i6.WasteClassification> applyFiltersToClassifications(
    List<_i6.WasteClassification>? classifications,
    _i7.FilterOptions? filterOptions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFiltersToClassifications,
          [
            classifications,
            filterOptions,
          ],
        ),
        returnValue: <_i6.WasteClassification>[],
      ) as List<_i6.WasteClassification>);

  @override
  _i4.Future<int> cleanupDuplicateClassifications() => (super.noSuchMethod(
        Invocation.method(
          #cleanupDuplicateClassifications,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [GamificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationService extends _i1.Mock
    implements _i9.GamificationService {
  MockGamificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initGamification() => (super.noSuchMethod(
        Invocation.method(
          #initGamification,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.GamificationProfile> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.GamificationProfile>.value(
            _FakeGamificationProfile_0(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.GamificationProfile>);

  @override
  _i4.Future<void> saveProfile(
          _i2.GamificationProfile? gamificationProfileToSave) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProfile,
          [gamificationProfileToSave],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Streak> updateStreak() => (super.noSuchMethod(
        Invocation.method(
          #updateStreak,
          [],
        ),
        returnValue: _i4.Future<_i2.Streak>.value(_FakeStreak_1(
          this,
          Invocation.method(
            #updateStreak,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Streak>);

  @override
  _i4.Future<_i2.UserPoints> addPoints(
    String? action, {
    String? category,
    int? customPoints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPoints,
          [action],
          {
            #category: category,
            #customPoints: customPoints,
          },
        ),
        returnValue: _i4.Future<_i2.UserPoints>.value(_FakeUserPoints_2(
          this,
          Invocation.method(
            #addPoints,
            [action],
            {
              #category: category,
              #customPoints: customPoints,
            },
          ),
        )),
      ) as _i4.Future<_i2.UserPoints>);

  @override
  _i4.Future<List<_i2.Challenge>> processClassification(
          _i6.WasteClassification? classification) =>
      (super.noSuchMethod(
        Invocation.method(
          #processClassification,
          [classification],
        ),
        returnValue: _i4.Future<List<_i2.Challenge>>.value(<_i2.Challenge>[]),
      ) as _i4.Future<List<_i2.Challenge>>);

  @override
  _i4.Future<void> processEducationalContent(
          _i10.EducationalContent? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #processEducationalContent,
          [content],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Achievement>> updateAchievementProgress(
    _i2.AchievementType? type,
    int? increment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAchievementProgress,
          [
            type,
            increment,
          ],
        ),
        returnValue:
            _i4.Future<List<_i2.Achievement>>.value(<_i2.Achievement>[]),
      ) as _i4.Future<List<_i2.Achievement>>);

  @override
  _i4.Future<List<_i2.Challenge>> getActiveChallenges() => (super.noSuchMethod(
        Invocation.method(
          #getActiveChallenges,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Challenge>>.value(<_i2.Challenge>[]),
      ) as _i4.Future<List<_i2.Challenge>>);

  @override
  _i4.Future<List<_i2.Challenge>> updateChallengeProgress(
          _i6.WasteClassification? classification) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChallengeProgress,
          [classification],
        ),
        returnValue: _i4.Future<List<_i2.Challenge>>.value(<_i2.Challenge>[]),
      ) as _i4.Future<List<_i2.Challenge>>);

  @override
  _i4.Future<List<_i2.WeeklyStats>> getWeeklyStats() => (super.noSuchMethod(
        Invocation.method(
          #getWeeklyStats,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.WeeklyStats>>.value(<_i2.WeeklyStats>[]),
      ) as _i4.Future<List<_i2.WeeklyStats>>);

  @override
  List<_i2.Achievement> getDefaultAchievements() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultAchievements,
          [],
        ),
        returnValue: <_i2.Achievement>[],
      ) as List<_i2.Achievement>);

  @override
  _i4.Future<void> clearGamificationData() => (super.noSuchMethod(
        Invocation.method(
          #clearGamificationData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getTotalLifetimePoints() => (super.noSuchMethod(
        Invocation.method(
          #getTotalLifetimePoints,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getArchivedPointsHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getArchivedPointsHistory,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> resetStreakToYesterday() => (super.noSuchMethod(
        Invocation.method(
          #resetStreakToYesterday,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.GamificationProfile> forceRefreshProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #forceRefreshProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.GamificationProfile>.value(
            _FakeGamificationProfile_0(
          this,
          Invocation.method(
            #forceRefreshProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.GamificationProfile>);

  @override
  _i4.Future<void> syncGamificationData() => (super.noSuchMethod(
        Invocation.method(
          #syncGamificationData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
