// Mocks generated by Mockito 5.4.4 from annotations
// in waste_segregation_app/test/screens/waste_dashboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i14;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:waste_segregation_app/models/classification_feedback.dart'
    as _i11;
import 'package:waste_segregation_app/models/educational_content.dart' as _i13;
import 'package:waste_segregation_app/models/filter_options.dart' as _i9;
import 'package:waste_segregation_app/models/gamification.dart' as _i5;
import 'package:waste_segregation_app/models/user_profile.dart' as _i7;
import 'package:waste_segregation_app/models/waste_classification.dart' as _i8;
import 'package:waste_segregation_app/services/classification_storage_service.dart'
    as _i2;
import 'package:waste_segregation_app/services/gamification_service.dart'
    as _i12;
import 'package:waste_segregation_app/services/storage_service.dart' as _i4;
import 'package:waste_segregation_app/services/user_profile_storage_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClassificationStorageService_0 extends _i1.SmartFake
    implements _i2.ClassificationStorageService {
  _FakeClassificationStorageService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserProfileStorageService_1 extends _i1.SmartFake
    implements _i3.UserProfileStorageService {
  _FakeUserProfileStorageService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClassificationSaveResult_2 extends _i1.SmartFake
    implements _i4.ClassificationSaveResult {
  _FakeClassificationSaveResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGamificationProfile_3 extends _i1.SmartFake
    implements _i5.GamificationProfile {
  _FakeGamificationProfile_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreak_4 extends _i1.SmartFake implements _i5.Streak {
  _FakeStreak_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserPoints_5 extends _i1.SmartFake implements _i5.UserPoints {
  _FakeUserPoints_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i4.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ClassificationStorageService get classificationStorage =>
      (super.noSuchMethod(
        Invocation.getter(#classificationStorage),
        returnValue: _FakeClassificationStorageService_0(
          this,
          Invocation.getter(#classificationStorage),
        ),
      ) as _i2.ClassificationStorageService);

  @override
  _i3.UserProfileStorageService get profileStorage => (super.noSuchMethod(
        Invocation.getter(#profileStorage),
        returnValue: _FakeUserProfileStorageService_1(
          this,
          Invocation.getter(#profileStorage),
        ),
      ) as _i3.UserProfileStorageService);

  @override
  _i6.Future<void> saveUserProfile(_i7.UserProfile? userProfile) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserProfile,
          [userProfile],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateTrainingConsent(
          _i7.TrainingConsent? trainingConsent) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTrainingConsent,
          [trainingConsent],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> grantTrainingConsent({required String? source}) =>
      (super.noSuchMethod(
        Invocation.method(
          #grantTrainingConsent,
          [],
          {#source: source},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> revokeTrainingConsent({String? source = r'settings'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeTrainingConsent,
          [],
          {#source: source},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.UserProfile?> getCurrentUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserProfile,
          [],
        ),
        returnValue: _i6.Future<_i7.UserProfile?>.value(),
      ) as _i6.Future<_i7.UserProfile?>);

  @override
  _i6.Future<void> clearUserInfo() => (super.noSuchMethod(
        Invocation.method(
          #clearUserInfo,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> saveClassification(
    _i8.WasteClassification? classification, {
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassification,
          [classification],
          {#force: force},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.ClassificationSaveResult> saveClassificationWithResult(
    _i8.WasteClassification? classification, {
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassificationWithResult,
          [classification],
          {#force: force},
        ),
        returnValue: _i6.Future<_i4.ClassificationSaveResult>.value(
            _FakeClassificationSaveResult_2(
          this,
          Invocation.method(
            #saveClassificationWithResult,
            [classification],
            {#force: force},
          ),
        )),
      ) as _i6.Future<_i4.ClassificationSaveResult>);

  @override
  _i6.Future<String?> findDuplicateClassificationId(
          _i8.WasteClassification? classification) =>
      (super.noSuchMethod(
        Invocation.method(
          #findDuplicateClassificationId,
          [classification],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<List<_i8.WasteClassification>> getAllClassifications(
          {_i9.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllClassifications,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i6.Future<List<_i8.WasteClassification>>.value(
            <_i8.WasteClassification>[]),
      ) as _i6.Future<List<_i8.WasteClassification>>);

  @override
  _i6.Future<List<_i8.WasteClassification>> getClassificationsWithPagination({
    _i9.FilterOptions? filterOptions,
    int? pageSize = 20,
    int? page = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsWithPagination,
          [],
          {
            #filterOptions: filterOptions,
            #pageSize: pageSize,
            #page: page,
          },
        ),
        returnValue: _i6.Future<List<_i8.WasteClassification>>.value(
            <_i8.WasteClassification>[]),
      ) as _i6.Future<List<_i8.WasteClassification>>);

  @override
  _i6.Future<int> getClassificationsCount({_i9.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationsCount,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<String> exportClassificationsToCSV(
          {_i9.FilterOptions? filterOptions}) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportClassificationsToCSV,
          [],
          {#filterOptions: filterOptions},
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #exportClassificationsToCSV,
            [],
            {#filterOptions: filterOptions},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> deleteClassification(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteClassification,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearAllClassifications,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveSettings({
    required bool? isDarkMode,
    required bool? isGoogleSyncEnabled,
    DateTime? lastCloudSync,
    bool? allowHistoryFeedback,
    int? feedbackTimeframeDays,
    bool? notifications,
    bool? eduNotifications,
    bool? gamificationNotifications,
    bool? reminderNotifications,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [],
          {
            #isDarkMode: isDarkMode,
            #isGoogleSyncEnabled: isGoogleSyncEnabled,
            #lastCloudSync: lastCloudSync,
            #allowHistoryFeedback: allowHistoryFeedback,
            #feedbackTimeframeDays: feedbackTimeframeDays,
            #notifications: notifications,
            #eduNotifications: eduNotifications,
            #gamificationNotifications: gamificationNotifications,
            #reminderNotifications: reminderNotifications,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateLastCloudSync(DateTime? timestamp) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastCloudSync,
          [timestamp],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<DateTime?> getLastCloudSync() => (super.noSuchMethod(
        Invocation.method(
          #getLastCloudSync,
          [],
        ),
        returnValue: _i6.Future<DateTime?>.value(),
      ) as _i6.Future<DateTime?>);

  @override
  _i6.Future<Map<String, dynamic>> getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i8.WasteClassification?> getCachedClassification(String? hash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedClassification,
          [hash],
        ),
        returnValue: _i6.Future<_i8.WasteClassification?>.value(),
      ) as _i6.Future<_i8.WasteClassification?>);

  @override
  _i6.Future<void> saveCachedClassification(
    String? hash,
    _i8.WasteClassification? classification,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCachedClassification,
          [
            hash,
            classification,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String> exportUserData() => (super.noSuchMethod(
        Invocation.method(
          #exportUserData,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #exportUserData,
            [],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> importUserData(String? jsonData) => (super.noSuchMethod(
        Invocation.method(
          #importUserData,
          [jsonData],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearClassifications() => (super.noSuchMethod(
        Invocation.method(
          #clearClassifications,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllUserData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllUserData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveAnalyticsEvents(List<dynamic>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalyticsEvents,
          [events],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> loadAnalyticsEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAnalyticsEvents,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<int> getGuestDataMigrationCount() => (super.noSuchMethod(
        Invocation.method(
          #getGuestDataMigrationCount,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> migrateGuestDataToCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #migrateGuestDataToCurrentUser,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  List<_i8.WasteClassification> applyFiltersToClassifications(
    List<_i8.WasteClassification>? classifications,
    _i9.FilterOptions? filterOptions,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyFiltersToClassifications,
          [
            classifications,
            filterOptions,
          ],
        ),
        returnValue: <_i8.WasteClassification>[],
      ) as List<_i8.WasteClassification>);

  @override
  _i6.Future<int> cleanupDuplicateClassifications() => (super.noSuchMethod(
        Invocation.method(
          #cleanupDuplicateClassifications,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> saveClassificationFeedback(
          _i11.ClassificationFeedback? feedback) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClassificationFeedback,
          [feedback],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i11.ClassificationFeedback?> getClassificationFeedback(
          String? dedupKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassificationFeedback,
          [dedupKey],
        ),
        returnValue: _i6.Future<_i11.ClassificationFeedback?>.value(),
      ) as _i6.Future<_i11.ClassificationFeedback?>);

  @override
  _i6.Future<List<_i11.ClassificationFeedback>>
      getAllClassificationFeedback() => (super.noSuchMethod(
            Invocation.method(
              #getAllClassificationFeedback,
              [],
            ),
            returnValue: _i6.Future<List<_i11.ClassificationFeedback>>.value(
                <_i11.ClassificationFeedback>[]),
          ) as _i6.Future<List<_i11.ClassificationFeedback>>);

  @override
  _i6.Future<void> migrateOldClassifications() => (super.noSuchMethod(
        Invocation.method(
          #migrateOldClassifications,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> migrateThumbnails() => (super.noSuchMethod(
        Invocation.method(
          #migrateThumbnails,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cleanUpOrphanedThumbnails() => (super.noSuchMethod(
        Invocation.method(
          #cleanUpOrphanedThumbnails,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> migrateImagePathsToRelative() => (super.noSuchMethod(
        Invocation.method(
          #migrateImagePathsToRelative,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [GamificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationService extends _i1.Mock
    implements _i12.GamificationService {
  MockGamificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> initGamification() => (super.noSuchMethod(
        Invocation.method(
          #initGamification,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i5.GamificationProfile> getProfile(
          {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i6.Future<_i5.GamificationProfile>.value(
            _FakeGamificationProfile_3(
          this,
          Invocation.method(
            #getProfile,
            [],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i6.Future<_i5.GamificationProfile>);

  @override
  _i6.Future<void> saveProfile(
          _i5.GamificationProfile? gamificationProfileToSave) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProfile,
          [gamificationProfileToSave],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i5.Streak> updateStreak() => (super.noSuchMethod(
        Invocation.method(
          #updateStreak,
          [],
        ),
        returnValue: _i6.Future<_i5.Streak>.value(_FakeStreak_4(
          this,
          Invocation.method(
            #updateStreak,
            [],
          ),
        )),
      ) as _i6.Future<_i5.Streak>);

  @override
  _i6.Future<_i5.UserPoints> addPoints(
    String? action, {
    String? category,
    int? customPoints,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPoints,
          [action],
          {
            #category: category,
            #customPoints: customPoints,
          },
        ),
        returnValue: _i6.Future<_i5.UserPoints>.value(_FakeUserPoints_5(
          this,
          Invocation.method(
            #addPoints,
            [action],
            {
              #category: category,
              #customPoints: customPoints,
            },
          ),
        )),
      ) as _i6.Future<_i5.UserPoints>);

  @override
  _i6.Future<void> syncClassificationPoints() => (super.noSuchMethod(
        Invocation.method(
          #syncClassificationPoints,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncAchievementProgressFromClassifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncAchievementProgressFromClassifications,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i5.Challenge>> processClassification(
          _i8.WasteClassification? classification) =>
      (super.noSuchMethod(
        Invocation.method(
          #processClassification,
          [classification],
        ),
        returnValue: _i6.Future<List<_i5.Challenge>>.value(<_i5.Challenge>[]),
      ) as _i6.Future<List<_i5.Challenge>>);

  @override
  _i6.Future<void> processEducationalContent(
          _i13.EducationalContent? content) =>
      (super.noSuchMethod(
        Invocation.method(
          #processEducationalContent,
          [content],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i5.Achievement>> updateAchievementProgress(
    _i5.AchievementType? type,
    int? increment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAchievementProgress,
          [
            type,
            increment,
          ],
        ),
        returnValue:
            _i6.Future<List<_i5.Achievement>>.value(<_i5.Achievement>[]),
      ) as _i6.Future<List<_i5.Achievement>>);

  @override
  _i6.Future<List<_i5.Challenge>> getActiveChallenges() => (super.noSuchMethod(
        Invocation.method(
          #getActiveChallenges,
          [],
        ),
        returnValue: _i6.Future<List<_i5.Challenge>>.value(<_i5.Challenge>[]),
      ) as _i6.Future<List<_i5.Challenge>>);

  @override
  _i6.Future<List<_i5.Challenge>> updateChallengeProgress(
          _i8.WasteClassification? classification) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChallengeProgress,
          [classification],
        ),
        returnValue: _i6.Future<List<_i5.Challenge>>.value(<_i5.Challenge>[]),
      ) as _i6.Future<List<_i5.Challenge>>);

  @override
  _i6.Future<List<_i5.WeeklyStats>> getWeeklyStats() => (super.noSuchMethod(
        Invocation.method(
          #getWeeklyStats,
          [],
        ),
        returnValue:
            _i6.Future<List<_i5.WeeklyStats>>.value(<_i5.WeeklyStats>[]),
      ) as _i6.Future<List<_i5.WeeklyStats>>);

  @override
  _i6.Future<void> trackWeeklyAction(
    String? action,
    String? category,
    int? pointsEarned,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackWeeklyAction,
          [
            action,
            category,
            pointsEarned,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<_i5.Achievement> getDefaultAchievements() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultAchievements,
          [],
        ),
        returnValue: <_i5.Achievement>[],
      ) as List<_i5.Achievement>);

  @override
  _i6.Future<void> clearGamificationData() => (super.noSuchMethod(
        Invocation.method(
          #clearGamificationData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> getTotalLifetimePoints() => (super.noSuchMethod(
        Invocation.method(
          #getTotalLifetimePoints,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getArchivedPointsHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getArchivedPointsHistory,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> resetStreakToYesterday() => (super.noSuchMethod(
        Invocation.method(
          #resetStreakToYesterday,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i5.GamificationProfile> forceRefreshProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #forceRefreshProfile,
          [],
        ),
        returnValue: _i6.Future<_i5.GamificationProfile>.value(
            _FakeGamificationProfile_3(
          this,
          Invocation.method(
            #forceRefreshProfile,
            [],
          ),
        )),
      ) as _i6.Future<_i5.GamificationProfile>);

  @override
  _i6.Future<void> forceCompleteSyncAndRefresh() => (super.noSuchMethod(
        Invocation.method(
          #forceCompleteSyncAndRefresh,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncGamificationData() => (super.noSuchMethod(
        Invocation.method(
          #syncGamificationData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncWeeklyStatsWithClassifications() => (super.noSuchMethod(
        Invocation.method(
          #syncWeeklyStatsWithClassifications,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i5.NearMilestoneNudge?> getNearMilestoneNudge() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearMilestoneNudge,
          [],
        ),
        returnValue: _i6.Future<_i5.NearMilestoneNudge?>.value(),
      ) as _i6.Future<_i5.NearMilestoneNudge?>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
