schemaVersion: 1
sessionDefaults:
  workspacePath: /Users/pranay/Projects/LLM/image/waste_seg/waste_segregation_app/ios/Runner.xcworkspace
  scheme: Runner
  configuration: Debug
  simulatorId: 99B3D785-20D8-4889-9622-43F89781AD9A
  suppressWarnings: true
  bundleId: com.example.wasteSegregationApp
  simulatorName: DailyHue iPhone 16
  simulatorPlatform: iOS Simulator
