#!/usr/bin/env bash
# Generate release evidence (RELEASE-PROOF-01, Commit 7).
#
# Produces docs/release/evidence/<version>/<sha>/RELEASE_EVIDENCE.md capturing
# SHA, tool versions, config hashes, test totals, artifact checksums and
# rollback commands so "production ready" claims are verifiable.
#
# Usage:
#   tools/generate_release_evidence.sh <version> [<sha>]
#     version  - e.g. 0.9.0 (must match a git tag or a release candidate label)
#     sha      - optional; defaults to HEAD. May be a full or short SHA.
#
# Env (optional, used when running inside GitHub Actions):
#   GITHUB_SHA / GITHUB_RUN_ID / GITHUB_WORKFLOW / GITHUB_RUN_NUMBER
#
# Exit codes: 0 on success, 1 if version is missing or git state is unusable.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
  echo "Usage: $0 <version> [<sha>]" >&2
  exit 1
fi

SHA="${2:-${GITHUB_SHA:-$(git rev-parse HEAD 2>/dev/null || echo UNVERIFIED)}}"
if [ "$SHA" = "UNVERIFIED" ] || ! git rev-parse --verify "$SHA" >/dev/null 2>&1; then
  # Accept the GitHub-provided SHA without requiring a local ref for it.
  if [ -z "${GITHUB_SHA:-}" ]; then
    echo "FAIL: cannot resolve SHA '$SHA' — is this a git checkout?" >&2
    exit 1
  fi
fi

OUT_DIR="docs/release/evidence/${VERSION}/${SHA}"
mkdir -p "$OUT_DIR"
OUT_FILE="${OUT_DIR}/RELEASE_EVIDENCE.md"

# --- Tool versions (verified at runtime; never guessed) --------------------
FLUTTER_VER="$(flutter --version 2>/dev/null | head -1 || echo UNVERIFIED)"
DART_VER="$(dart --version 2>&1 | head -1 || echo UNVERIFIED)"
NODE_VER="$(node --version 2>/dev/null || echo UNVERIFIED)"

# --- Config hashes ----------------------------------------------------------
hash_file() {
  if [ -f "$1" ]; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    echo "MISSING"
  fi
}
PUBSPEC_HASH="$(hash_file pubspec.yaml)"
FUNCTIONS_PKG_HASH="$(hash_file functions/package.json)"
RULES_HASH="$(hash_file firestore.rules)"
STORAGE_RULES_HASH="$(hash_file storage.rules)"

# --- Test totals (from flutter test --machine, best-effort) -----------------
TEST_TOTAL="UNVERIFIED"
TEST_PASSED="UNVERIFIED"
TEST_FAILED="UNVERIFIED"
if [ -f build/reports/tests/test_summary.json ]; then
  TEST_TOTAL="$(python3 -c 'import json;d=json.load(open("build/reports/tests/test_summary.json"));print(d.get("total","UNVERIFIED"))' 2>/dev/null || echo UNVERIFIED)"
  TEST_PASSED="$(python3 -c 'import json;d=json.load(open("build/reports/tests/test_summary.json"));print(d.get("passed","UNVERIFIED"))' 2>/dev/null || echo UNVERIFIED)"
  TEST_FAILED="$(python3 -c 'import json;d=json.load(open("build/reports/tests/test_summary.json"));print(d.get("failed","UNVERIFIED"))' 2>/dev/null || echo UNVERIFIED)"
fi

# --- Eval report (build/reports/eval is the CI artifact location) ----------
EVAL_PATH="build/reports/eval/ci_eval_report.json"
EVAL_SUMMARY="UNVERIFIED"
if [ -f "$EVAL_PATH" ]; then
  EVAL_SUMMARY="$(python3 -c '
import json
d = json.load(open("'$EVAL_PATH'"))
best = d.get("ranking", [{}])[0]
print(f"golden_cases={d.get(\"golden_case_count\",\"?\")} best_strict={best.get(\"strict_pass_rate\",\"?\")} safety_failures={best.get(\"safety_failures\",\"?\")} must_not_violations={best.get(\"must_not_violations\",\"?\")}")
' 2>/dev/null || echo UNVERIFIED)"
fi

# --- Artifact checksums -------------------------------------------------------
ARTIFACT_SHA=""
for f in \
  build/app/outputs/flutter-apk/app-release.apk \
  build/app/outputs/bundle/release/app-release.aab; do
  if [ -f "$f" ]; then
    ARTIFACT_SHA="${ARTIFACT_SHA}\n- \`${f}\`: \`$(shasum -a 256 "$f" | awk '{print $1}')\`"
  fi
done
[ -z "$ARTIFACT_SHA" ] && ARTIFACT_SHA="\n- (no local release artifacts found — build on the release runner)"

# --- Rollback commands -------------------------------------------------------
ROLLBACK="$(cat <<'RB'
# Rollback to the previous release:
# 1. Redeploy Functions from the previous tag:
#    git checkout <previous-tag> && (cd functions && npm ci && npm run build && npm run deploy)
# 2. Redeploy rules:
#    firebase deploy --only firestore:rules,storage
# 3. Redeploy hosting:
#    firebase deploy --only hosting
# 4. Consider Remote Config rollback in the Firebase console if feature
#    flags shipped with this release contributed to the incident.
RB
)"

NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "$OUT_FILE" <<EOF
# Release Evidence

> Generated by \`tools/generate_release_evidence.sh\` (RELEASE-PROOF-01, Commit 7).
> Facts below are read from the environment/workflow at generation time;
> anything not available is written as \`UNVERIFIED\` rather than guessed.

## Release
- version: \`${VERSION}\`
- commit: \`${SHA}\`
- generated_at: \`${NOW}\`

## Toolchain
- flutter: \`${FLUTTER_VER}\`
- dart: \`${DART_VER}\`
- node: \`${NODE_VER}\`

## CI
- workflow: \`${GITHUB_WORKFLOW:-UNVERIFIED}\`
- run_id: \`${GITHUB_RUN_ID:-UNVERIFIED}\`
- run_number: \`${GITHUB_RUN_NUMBER:-UNVERIFIED}\`

## Config hashes (SHA-256)
- pubspec.yaml: \`${PUBSPEC_HASH}\`
- functions/package.json: \`${FUNCTIONS_PKG_HASH}\`
- firestore.rules: \`${RULES_HASH}\`
- storage.rules: \`${STORAGE_RULES_HASH}\`

## Tests
- total: \`${TEST_TOTAL}\`
- passed: \`${TEST_PASSED}\`
- failed: \`${TEST_FAILED}\`

## Eval report
- \`${EVAL_PATH}\`
- summary: \`${EVAL_SUMMARY}\`

## Artifacts (SHA-256)
${ARTIFACT_SHA}

## Deployed
- Functions version: UNVERIFIED (populate from \`firebase functions:list\` / deploy log)
- Rules deployment: UNVERIFIED (populate from deploy log)
- Hosting config: UNVERIFIED

## Smoke evidence
- UNVERIFIED — run the staging smoke checklist (Commit 6) and link the run here.

## Known exceptions
- (list any accepted deviations from the release gates and why)

## Rollback
\`\`\`bash
${ROLLBACK}
\`\`\`
EOF

echo "Wrote $OUT_FILE"
